export interface IScoreBMWP {
    // family:            string,
    common_name:       string,
    score_orig:        number,
    score_rev:         number | null,
    score_riffle:      number | null,
    score_riffle_pool: number | null,
    score_pool:        number | null,
}

const scoresBmwp: Map<string, IScoreBMWP> = new Map([
	["Planariidae",           { "common_name":" Flatworms",           "score_orig":5,  "score_rev":4.2,  "score_riffle":4.5,  "score_riffle_pool":4.1,  "score_pool":3.7  }],
	["Dendrocoelidae",        { "common_name":" Flatworms",           "score_orig":5,  "score_rev":3.1,  "score_riffle":2.3,  "score_riffle_pool":4.1,  "score_pool":3.1  }],
	["Neritidae",             { "common_name":" Snails",              "score_orig":6,  "score_rev":7.5,  "score_riffle":6.7,  "score_riffle_pool":8.1,  "score_pool":9.3  }],
	["Viviparidae",           { "common_name":" Snails",              "score_orig":6,  "score_rev":6.3,  "score_riffle":2.1,  "score_riffle_pool":4.7,  "score_pool":7.1  }],
	["Valvatidae",            { "common_name":" Snails",              "score_orig":3,  "score_rev":2.8,  "score_riffle":2.5,  "score_riffle_pool":2.5,  "score_pool":3.2  }],
	["Hydrobiidae",           { "common_name":" Snails",              "score_orig":3,  "score_rev":3.9,  "score_riffle":4.1,  "score_riffle_pool":3.9,  "score_pool":3.7  }],
	["Lymnaeidae",            { "common_name":" Snails",              "score_orig":3,  "score_rev":3,    "score_riffle":3.2,  "score_riffle_pool":3.1,  "score_pool":2.8  }],
	["Physidae",              { "common_name":" Snails",              "score_orig":3,  "score_rev":1.8,  "score_riffle":0.9,  "score_riffle_pool":1.5,  "score_pool":2.8  }],
	["Planorbidae",           { "common_name":" Snails",              "score_orig":3,  "score_rev":2.9,  "score_riffle":2.6,  "score_riffle_pool":2.9,  "score_pool":3.1  }],
	["Ancylidae",             { "common_name":" Limpets and Mussels", "score_orig":6,  "score_rev":5.6,  "score_riffle":5.5,  "score_riffle_pool":5.5,  "score_pool":6.2  }],
	["Unionidae",             { "common_name":" Limpets and Mussels", "score_orig":6,  "score_rev":5.2,  "score_riffle":4.7,  "score_riffle_pool":4.8,  "score_pool":5.5  }],
	["Sphaeriidae",           { "common_name":" Limpets and Mussels", "score_orig":3,  "score_rev":3.6,  "score_riffle":3.7,  "score_riffle_pool":3.7,  "score_pool":3.4  }],
	["Oligochaeta",           { "common_name":" Worms",               "score_orig":1,  "score_rev":3.5,  "score_riffle":3.9,  "score_riffle_pool":3.2,  "score_pool":2.5  }],
	["Piscicolidae",          { "common_name":" Leeches",             "score_orig":4,  "score_rev":5,    "score_riffle":4.5,  "score_riffle_pool":5.4,  "score_pool":5.2  }],
	["Glossiphoniidae",       { "common_name":" Leeches",             "score_orig":3,  "score_rev":3.1,  "score_riffle":3,    "score_riffle_pool":3.3,  "score_pool":2.9  }],
	["Hirudididae",           { "common_name":" Leeches",             "score_orig":3,  "score_rev":0,    "score_riffle":0.3,  "score_riffle_pool":-0.3, "score_pool":null }],
	["Erpobdellidae",         { "common_name":" Leeches",             "score_orig":3,  "score_rev":2.8,  "score_riffle":2.8,  "score_riffle_pool":2.8,  "score_pool":2.6  }],
	["Asellidae",             { "common_name":" Crustaceans",         "score_orig":3,  "score_rev":2.1,  "score_riffle":1.5,  "score_riffle_pool":2.4,  "score_pool":2.7  }],
	["Corophiidae",           { "common_name":" Crustaceans",         "score_orig":6,  "score_rev":6.1,  "score_riffle":5.4,  "score_riffle_pool":5.1,  "score_pool":6.5  }],
	["Gammaridae",            { "common_name":" Crustaceans",         "score_orig":6,  "score_rev":4.5,  "score_riffle":4.7,  "score_riffle_pool":4.3,  "score_pool":4.3  }],
	["Astacidae",             { "common_name":" Crustaceans",         "score_orig":8,  "score_rev":9,    "score_riffle":8.8,  "score_riffle_pool":9,    "score_pool":11.2 }],
	["Siphlonuridae",         { "common_name":" Mayflies",            "score_orig":10, "score_rev":11,   "score_riffle":11,   "score_riffle_pool":null, "score_pool":null }],
	["Baetidae",              { "common_name":" Mayflies",            "score_orig":4,  "score_rev":5.3,  "score_riffle":5.5,  "score_riffle_pool":4.8,  "score_pool":5.1  }],
	["Heptageniidae",         { "common_name":" Mayflies",            "score_orig":10, "score_rev":9.8,  "score_riffle":9.7,  "score_riffle_pool":10.7, "score_pool":13   }],
	["Leptophlebiidae",       { "common_name":" Mayflies",            "score_orig":10, "score_rev":8.9,  "score_riffle":8.7,  "score_riffle_pool":8.9,  "score_pool":9.9  }],
	["Ephemerellidae",        { "common_name":" Mayflies",            "score_orig":10, "score_rev":7.7,  "score_riffle":7.6,  "score_riffle_pool":8.1,  "score_pool":9.3  }],
	["Potamanthidae",         { "common_name":" Mayflies",            "score_orig":10, "score_rev":7.6,  "score_riffle":7.6,  "score_riffle_pool":null, "score_pool":null }],
	["Ephemeridae",           { "common_name":" Mayflies",            "score_orig":10, "score_rev":9.3,  "score_riffle":9,    "score_riffle_pool":9.2,  "score_pool":11   }],
	["Caenidae",              { "common_name":" Mayflies",            "score_orig":7,  "score_rev":7.1,  "score_riffle":7.2,  "score_riffle_pool":7.3,  "score_pool":6.4  }],
	["Taeniopterygidae",      { "common_name":" Stoneflies",          "score_orig":10, "score_rev":10.8, "score_riffle":10.7, "score_riffle_pool":12.1, "score_pool":null }],
	["Nemouridae",            { "common_name":" Stoneflies",          "score_orig":7,  "score_rev":9.1,  "score_riffle":9.2,  "score_riffle_pool":8.5,  "score_pool":8.8  }],
	["Leuctridae",            { "common_name":" Stoneflies",          "score_orig":10, "score_rev":9.9,  "score_riffle":9.8,  "score_riffle_pool":10.4, "score_pool":11.2 }],
	["Capniidae",             { "common_name":" Stoneflies",          "score_orig":10, "score_rev":10,   "score_riffle":10.1, "score_riffle_pool":null, "score_pool":null }],
	["Perlodidae",            { "common_name":" Stoneflies",          "score_orig":10, "score_rev":10.7, "score_riffle":10.8, "score_riffle_pool":10.7, "score_pool":10.9 }],
	["Perlidae",              { "common_name":" Stoneflies",          "score_orig":10, "score_rev":12.5, "score_riffle":12.5, "score_riffle_pool":12.2, "score_pool":null }],
	["Chloroperlidae",        { "common_name":" Stoneflies",          "score_orig":10, "score_rev":12.4, "score_riffle":12.5, "score_riffle_pool":12.1, "score_pool":null }],
	["Platycnemidae",         { "common_name":" Damselflies",         "score_orig":6,  "score_rev":5.1,  "score_riffle":3.6,  "score_riffle_pool":5.4,  "score_pool":5.7  }],
	["Coenagriidae",          { "common_name":" Damselflies",         "score_orig":6,  "score_rev":3.5,  "score_riffle":2.6,  "score_riffle_pool":3.3,  "score_pool":3.8  }],
	["Lestidae",              { "common_name":" Damselflies",         "score_orig":8,  "score_rev":5.4,  "score_riffle":null, "score_riffle_pool":null, "score_pool":5.4  }],
	["Calopterygidae",        { "common_name":" Damselflies",         "score_orig":8,  "score_rev":6.4,  "score_riffle":6,    "score_riffle_pool":6.1,  "score_pool":7.6  }],
	["Gomphidae",             { "common_name":" Dragonflies",         "score_orig":8,  "score_rev":null, "score_riffle":null, "score_riffle_pool":null, "score_pool":null }],
	["Cordulegasteridae",     { "common_name":" Dragonflies",         "score_orig":8,  "score_rev":8.6,  "score_riffle":9.5,  "score_riffle_pool":6.5,  "score_pool":7.6  }],
	["Aeshnidae",             { "common_name":" Dragonflies",         "score_orig":8,  "score_rev":6.1,  "score_riffle":7,    "score_riffle_pool":6.9,  "score_pool":5.7  }],
	["Corduliidae",           { "common_name":" Dragonflies",         "score_orig":8,  "score_rev":null, "score_riffle":null, "score_riffle_pool":null, "score_pool":null }],
	["Libellulidae",          { "common_name":" Dragonflies",         "score_orig":8,  "score_rev":5,    "score_riffle":null, "score_riffle_pool":null, "score_pool":5    }],
	// ["Mesoveliidae *",    { "common_name":" Bugs",                "score_orig":5,  "score_rev":4.7,  "score_riffle":4.9,  "score_riffle_pool":4,    "score_pool":5.1}],
	["Hydrometridae",         { "common_name":" Bugs",                "score_orig":5,  "score_rev":5.3,  "score_riffle":5,    "score_riffle_pool":6.2,  "score_pool":4.9  }],
	["Gerridae",              { "common_name":" Bugs",                "score_orig":5,  "score_rev":4.7,  "score_riffle":4.5,  "score_riffle_pool":5,    "score_pool":4.7  }],
	["Nepidae",               { "common_name":" Bugs",                "score_orig":5,  "score_rev":4.3,  "score_riffle":4.1,  "score_riffle_pool":4.2,  "score_pool":4.5  }],
	["Naucoridae",            { "common_name":" Bugs",                "score_orig":5,  "score_rev":4.3,  "score_riffle":null, "score_riffle_pool":null, "score_pool":4.3  }],
	["Aphelocheiridae",       { "common_name":" Bugs",                "score_orig":10, "score_rev":8.9,  "score_riffle":8.4,  "score_riffle_pool":9.5,  "score_pool":11.7 }],
	["Notonectidae",          { "common_name":" Bugs",                "score_orig":5,  "score_rev":3.8,  "score_riffle":1.8,  "score_riffle_pool":3.4,  "score_pool":4.4  }],
	["Pleidae",               { "common_name":" Bugs",                "score_orig":5,  "score_rev":3.9,  "score_riffle":null, "score_riffle_pool":null, "score_pool":3.9  }],
	["Corixidae",             { "common_name":" Bugs",                "score_orig":5,  "score_rev":3.7,  "score_riffle":3.6,  "score_riffle_pool":3.5,  "score_pool":3.9  }],
	["Haliplidae",            { "common_name":" Beetles",             "score_orig":5,  "score_rev":4,    "score_riffle":3.7,  "score_riffle_pool":4.2,  "score_pool":4.3  }],
	["Hygrobiidae",           { "common_name":" Beetles",             "score_orig":5,  "score_rev":2.6,  "score_riffle":5.6,  "score_riffle_pool":-0.8, "score_pool":2.6  }],
	["Dytiscidae",            { "common_name":" Beetles",             "score_orig":5,  "score_rev":4.8,  "score_riffle":5.2,  "score_riffle_pool":4.3,  "score_pool":4.2  }],
	["Gyrinidae",             { "common_name":" Beetles",             "score_orig":5,  "score_rev":7.8,  "score_riffle":8.1,  "score_riffle_pool":7.4,  "score_pool":6.8  }],
	["Hydrophilidae",         { "common_name":" Beetles",             "score_orig":5,  "score_rev":5.1,  "score_riffle":5.5,  "score_riffle_pool":4.5,  "score_pool":3.9  }],
	["Clambidae",             { "common_name":" Beetles",             "score_orig":5,  "score_rev":null, "score_riffle":null, "score_riffle_pool":null, "score_pool":null }],
	["Scirtidae",             { "common_name":" Beetles",             "score_orig":5,  "score_rev":6.5,  "score_riffle":6.9,  "score_riffle_pool":6.2,  "score_pool":5.8  }],
	["Dryopidae",             { "common_name":" Beetles",             "score_orig":5,  "score_rev":6.5,  "score_riffle":6.5,  "score_riffle_pool":null, "score_pool":null }],
	["Elmidae",               { "common_name":" Beetles",             "score_orig":5,  "score_rev":6.4,  "score_riffle":6.5,  "score_riffle_pool":6.1,  "score_pool":6.5  }],
	// ["Chrysomelidae *",   { "common_name":" Beetles",             "score_orig":5,  "score_rev":4.2,  "score_riffle":4.9,  "score_riffle_pool":1.1,  "score_pool":4.1}],
	// ["Curculionidae *",   { "common_name":" Beetles",             "score_orig":5,  "score_rev":4,    "score_riffle":4.7,  "score_riffle_pool":3.1,  "score_pool":2.9}],
	["Sialidae",              { "common_name":" Alderflies",          "score_orig":4,  "score_rev":4.5,  "score_riffle":4.7,  "score_riffle_pool":4.7,  "score_pool":4.3  }],
	["Rhyacophilidae",        { "common_name":" Caddisflies",         "score_orig":7,  "score_rev":8.3,  "score_riffle":8.2,  "score_riffle_pool":8.6,  "score_pool":9.6  }],
	["Philopotamidae",        { "common_name":" Caddisflies",         "score_orig":8,  "score_rev":10.6, "score_riffle":10.7, "score_riffle_pool":9.8,  "score_pool":null }],
	["Polycentropidae",       { "common_name":" Caddisflies",         "score_orig":7,  "score_rev":8.6,  "score_riffle":8.6,  "score_riffle_pool":8.4,  "score_pool":8.7  }],
	["Psychomyiidae",         { "common_name":" Caddisflies",         "score_orig":8,  "score_rev":6.9,  "score_riffle":6.4,  "score_riffle_pool":7.4,  "score_pool":8    }],
	["Hydropsychidae",        { "common_name":" Caddisflies",         "score_orig":5,  "score_rev":6.6,  "score_riffle":6.6,  "score_riffle_pool":6.5,  "score_pool":7.2  }],
	["Hydroptilidae",         { "common_name":" Caddisflies",         "score_orig":6,  "score_rev":6.7,  "score_riffle":6.7,  "score_riffle_pool":6.8,  "score_pool":6.5  }],
	["Phryganeidae",          { "common_name":" Caddisflies",         "score_orig":10, "score_rev":7,    "score_riffle":6.6,  "score_riffle_pool":5.4,  "score_pool":8    }],
	["Limnephilidae",         { "common_name":" Caddisflies",         "score_orig":7,  "score_rev":6.9,  "score_riffle":7.1,  "score_riffle_pool":6.5,  "score_pool":6.6  }],
	["Molannidae",            { "common_name":" Caddisflies",         "score_orig":10, "score_rev":8.9,  "score_riffle":7.8,  "score_riffle_pool":8.1,  "score_pool":10   }],
	["Beraeidae",             { "common_name":" Caddisflies",         "score_orig":10, "score_rev":9,    "score_riffle":8.3,  "score_riffle_pool":7.8,  "score_pool":10   }],
	["Odontoceridae",         { "common_name":" Caddisflies",         "score_orig":10, "score_rev":10.9, "score_riffle":10.8, "score_riffle_pool":11.4, "score_pool":11.7 }],
	["Leptoceridae",          { "common_name":" Caddisflies",         "score_orig":10, "score_rev":7.8,  "score_riffle":7.8,  "score_riffle_pool":7.7,  "score_pool":8.1  }],
	["Goeridae",              { "common_name":" Caddisflies",         "score_orig":10, "score_rev":9.9,  "score_riffle":9.8,  "score_riffle_pool":9.6,  "score_pool":12.4 }],
	["Lepidostomatidae",      { "common_name":" Caddisflies",         "score_orig":10, "score_rev":10.4, "score_riffle":10.3, "score_riffle_pool":10.7, "score_pool":11.6 }],
	["Brachycentridae",       { "common_name":" Caddisflies",         "score_orig":10, "score_rev":9.4,  "score_riffle":9.3,  "score_riffle_pool":9.7,  "score_pool":11   }],
	["Sericostomatidae",      { "common_name":" Caddisflies",         "score_orig":10, "score_rev":9.2,  "score_riffle":9.1,  "score_riffle_pool":9.3,  "score_pool":10.3 }],
	["Tipulidae",             { "common_name":" True flies",          "score_orig":5,  "score_rev":5.5,  "score_riffle":5.6,  "score_riffle_pool":5,    "score_pool":5.1  }],
	["Chironomidae",          { "common_name":" True flies",          "score_orig":2,  "score_rev":3.7,  "score_riffle":4.1,  "score_riffle_pool":3.4,  "score_pool":2.8  }],
	["Simuliidae",            { "common_name":" True flies",          "score_orig":5,  "score_rev":5.8,  "score_riffle":5.9,  "score_riffle_pool":5.1,  "score_pool":5.5  }],
]);

// Source: http://www.cies.staffs.ac.uk/bmwptabl.htm
//
//  * These families are now excluded from the list used for the calculation of the score.
//    A blank indicates that there were insufficient records for the calculations.
//
// The Revised BMWP Scores are based on the analysis of frequency of occurrence of the families
// recorded in approximately 17,000 samples.
//
// The Habitat Specific Scores are based on the following substrate compositions:
// Riffles: >= 70% boulders and pebbles    Pool: >= 70% sand and silt    Riffle/Pool: the remainder


export default scoresBmwp;
