export interface IScoreBMWP {
    common_name:        string,
    family:             string,
    score_orig:         number,
    score:              number | null,
    score_riffles:      number | null,
    score_riffle_pools: number | null,
    score_pools:        number | null,
}

const scoresBmwp: IScoreBMWP[] = [
	{"common_name":"Flatworms",           "family":"Planariidae",       "score":4.2,  "score_orig":5,  "score_riffles":4.5,  "score_riffle_pools":4.1,  "score_pools":3.7},
	{"common_name":"Flatworms",           "family":"Dendrocoelidae",    "score":3.1,  "score_orig":5,  "score_riffles":2.3,  "score_riffle_pools":4.1,  "score_pools":3.1},
	{"common_name":"Snails",              "family":"Neritidae",         "score":7.5,  "score_orig":6,  "score_riffles":6.7,  "score_riffle_pools":8.1,  "score_pools":9.3},
	{"common_name":"Snails",              "family":"Viviparidae",       "score":6.3,  "score_orig":6,  "score_riffles":2.1,  "score_riffle_pools":4.7,  "score_pools":7.1},
	{"common_name":"Snails",              "family":"Valvatidae",        "score":2.8,  "score_orig":3,  "score_riffles":2.5,  "score_riffle_pools":2.5,  "score_pools":3.2},
	{"common_name":"Snails",              "family":"Hydrobiidae",       "score":3.9,  "score_orig":3,  "score_riffles":4.1,  "score_riffle_pools":3.9,  "score_pools":3.7},
	{"common_name":"Snails",              "family":"Lymnaeidae",        "score":3,    "score_orig":3,  "score_riffles":3.2,  "score_riffle_pools":3.1,  "score_pools":2.8},
	{"common_name":"Snails",              "family":"Physidae",          "score":1.8,  "score_orig":3,  "score_riffles":0.9,  "score_riffle_pools":1.5,  "score_pools":2.8},
	{"common_name":"Snails",              "family":"Planorbidae",       "score":2.9,  "score_orig":3,  "score_riffles":2.6,  "score_riffle_pools":2.9,  "score_pools":3.1},
	{"common_name":"Limpets and Mussels", "family":"Ancylidae",         "score":5.6,  "score_orig":6,  "score_riffles":5.5,  "score_riffle_pools":5.5,  "score_pools":6.2},
	{"common_name":"Limpets and Mussels", "family":"Unionidae",         "score":5.2,  "score_orig":6,  "score_riffles":4.7,  "score_riffle_pools":4.8,  "score_pools":5.5},
	{"common_name":"Limpets and Mussels", "family":"Sphaeriidae",       "score":3.6,  "score_orig":3,  "score_riffles":3.7,  "score_riffle_pools":3.7,  "score_pools":3.4},
	{"common_name":"Worms",               "family":"Oligochaeta",       "score":3.5,  "score_orig":1,  "score_riffles":3.9,  "score_riffle_pools":3.2,  "score_pools":2.5},
	{"common_name":"Leeches",             "family":"Piscicolidae",      "score":5,    "score_orig":4,  "score_riffles":4.5,  "score_riffle_pools":5.4,  "score_pools":5.2},
	{"common_name":"Leeches",             "family":"Glossiphoniidae",   "score":3.1,  "score_orig":3,  "score_riffles":3,    "score_riffle_pools":3.3,  "score_pools":2.9},
	{"common_name":"Leeches",             "family":"Hirudididae",       "score":0,    "score_orig":3,  "score_riffles":0.3,  "score_riffle_pools":-0.3, "score_pools":null },
	{"common_name":"Leeches",             "family":"Erpobdellidae",     "score":2.8,  "score_orig":3,  "score_riffles":2.8,  "score_riffle_pools":2.8,  "score_pools":2.6},
	{"common_name":"Crustaceans",         "family":"Asellidae",         "score":2.1,  "score_orig":3,  "score_riffles":1.5,  "score_riffle_pools":2.4,  "score_pools":2.7},
	{"common_name":"Crustaceans",         "family":"Corophiidae",       "score":6.1,  "score_orig":6,  "score_riffles":5.4,  "score_riffle_pools":5.1,  "score_pools":6.5},
	{"common_name":"Crustaceans",         "family":"Gammaridae",        "score":4.5,  "score_orig":6,  "score_riffles":4.7,  "score_riffle_pools":4.3,  "score_pools":4.3},
	{"common_name":"Crustaceans",         "family":"Astacidae",         "score":9,    "score_orig":8,  "score_riffles":8.8,  "score_riffle_pools":9,    "score_pools":11.2},
	{"common_name":"Mayflies",            "family":"Siphlonuridae",     "score":11,   "score_orig":10, "score_riffles":11,   "score_riffle_pools":null, "score_pools":null },
	{"common_name":"Mayflies",            "family":"Baetidae",          "score":5.3,  "score_orig":4,  "score_riffles":5.5,  "score_riffle_pools":4.8,  "score_pools":5.1},
	{"common_name":"Mayflies",            "family":"Heptageniidae",     "score":9.8,  "score_orig":10, "score_riffles":9.7,  "score_riffle_pools":10.7, "score_pools":13},
	{"common_name":"Mayflies",            "family":"Leptophlebiidae",   "score":8.9,  "score_orig":10, "score_riffles":8.7,  "score_riffle_pools":8.9,  "score_pools":9.9},
	{"common_name":"Mayflies",            "family":"Ephemerellidae",    "score":7.7,  "score_orig":10, "score_riffles":7.6,  "score_riffle_pools":8.1,  "score_pools":9.3},
	{"common_name":"Mayflies",            "family":"Potamanthidae",     "score":7.6,  "score_orig":10, "score_riffles":7.6,  "score_riffle_pools":null, "score_pools":null },
	{"common_name":"Mayflies",            "family":"Ephemeridae",       "score":9.3,  "score_orig":10, "score_riffles":9,    "score_riffle_pools":9.2,  "score_pools":11},
	{"common_name":"Mayflies",            "family":"Caenidae",          "score":7.1,  "score_orig":7,  "score_riffles":7.2,  "score_riffle_pools":7.3,  "score_pools":6.4},
	{"common_name":"Stoneflies",          "family":"Taeniopterygidae",  "score":10.8, "score_orig":10, "score_riffles":10.7, "score_riffle_pools":12.1, "score_pools":null },
	{"common_name":"Stoneflies",          "family":"Nemouridae",        "score":9.1,  "score_orig":7,  "score_riffles":9.2,  "score_riffle_pools":8.5,  "score_pools":8.8},
	{"common_name":"Stoneflies",          "family":"Leuctridae",        "score":9.9,  "score_orig":10, "score_riffles":9.8,  "score_riffle_pools":10.4, "score_pools":11.2},
	{"common_name":"Stoneflies",          "family":"Capniidae",         "score":10,   "score_orig":10, "score_riffles":10.1, "score_riffle_pools":null, "score_pools":null },
	{"common_name":"Stoneflies",          "family":"Perlodidae",        "score":10.7, "score_orig":10, "score_riffles":10.8, "score_riffle_pools":10.7, "score_pools":10.9},
	{"common_name":"Stoneflies",          "family":"Perlidae",          "score":12.5, "score_orig":10, "score_riffles":12.5, "score_riffle_pools":12.2, "score_pools":null },
	{"common_name":"Stoneflies",          "family":"Chloroperlidae",    "score":12.4, "score_orig":10, "score_riffles":12.5, "score_riffle_pools":12.1, "score_pools":null },
	{"common_name":"Damselflies",         "family":"Platycnemidae",     "score":5.1,  "score_orig":6,  "score_riffles":3.6,  "score_riffle_pools":5.4,  "score_pools":5.7},
	{"common_name":"Damselflies",         "family":"Coenagriidae",      "score":3.5,  "score_orig":6,  "score_riffles":2.6,  "score_riffle_pools":3.3,  "score_pools":3.8},
	{"common_name":"Damselflies",         "family":"Lestidae",          "score":5.4,  "score_orig":8,  "score_riffles":null, "score_riffle_pools":null, "score_pools":5.4},
	{"common_name":"Damselflies",         "family":"Calopterygidae",    "score":6.4,  "score_orig":8,  "score_riffles":6,    "score_riffle_pools":6.1,  "score_pools":7.6},
	{"common_name":"Dragonflies",         "family":"Gomphidae",         "score":null, "score_orig":8,  "score_riffles":null, "score_riffle_pools":null, "score_pools":null },
	{"common_name":"Dragonflies",         "family":"Cordulegasteridae", "score":8.6,  "score_orig":8,  "score_riffles":9.5,  "score_riffle_pools":6.5,  "score_pools":7.6},
	{"common_name":"Dragonflies",         "family":"Aeshnidae",         "score":6.1,  "score_orig":8,  "score_riffles":7,    "score_riffle_pools":6.9,  "score_pools":5.7},
	{"common_name":"Dragonflies",         "family":"Corduliidae",       "score":null, "score_orig":8,  "score_riffles":null, "score_riffle_pools":null, "score_pools":null },
	{"common_name":"Dragonflies",         "family":"Libellulidae",      "score":5,    "score_orig":8,  "score_riffles":null, "score_riffle_pools":null, "score_pools":5},
	{"common_name":"Bugs",                "family":"Mesoveliidae *",    "score":4.7,  "score_orig":5,  "score_riffles":4.9,  "score_riffle_pools":4,    "score_pools":5.1},
	{"common_name":"Bugs",                "family":"Hydrometridae",     "score":5.3,  "score_orig":5,  "score_riffles":5,    "score_riffle_pools":6.2,  "score_pools":4.9},
	{"common_name":"Bugs",                "family":"Gerridae",          "score":4.7,  "score_orig":5,  "score_riffles":4.5,  "score_riffle_pools":5,    "score_pools":4.7},
	{"common_name":"Bugs",                "family":"Nepidae",           "score":4.3,  "score_orig":5,  "score_riffles":4.1,  "score_riffle_pools":4.2,  "score_pools":4.5},
	{"common_name":"Bugs",                "family":"Naucoridae",        "score":4.3,  "score_orig":5,  "score_riffles":null, "score_riffle_pools":null, "score_pools":4.3},
	{"common_name":"Bugs",                "family":"Aphelocheiridae",   "score":8.9,  "score_orig":10, "score_riffles":8.4,  "score_riffle_pools":9.5,  "score_pools":11.7},
	{"common_name":"Bugs",                "family":"Notonectidae",      "score":3.8,  "score_orig":5,  "score_riffles":1.8,  "score_riffle_pools":3.4,  "score_pools":4.4},
	{"common_name":"Bugs",                "family":"Pleidae",           "score":3.9,  "score_orig":5,  "score_riffles":null, "score_riffle_pools":null, "score_pools":3.9},
	{"common_name":"Bugs",                "family":"Corixidae",         "score":3.7,  "score_orig":5,  "score_riffles":3.6,  "score_riffle_pools":3.5,  "score_pools":3.9},
	{"common_name":"Beetles",             "family":"Haliplidae",        "score":4,    "score_orig":5,  "score_riffles":3.7,  "score_riffle_pools":4.2,  "score_pools":4.3},
	{"common_name":"Beetles",             "family":"Hygrobiidae",       "score":2.6,  "score_orig":5,  "score_riffles":5.6,  "score_riffle_pools":-0.8, "score_pools":2.6},
	{"common_name":"Beetles",             "family":"Dytiscidae",        "score":4.8,  "score_orig":5,  "score_riffles":5.2,  "score_riffle_pools":4.3,  "score_pools":4.2},
	{"common_name":"Beetles",             "family":"Gyrinidae",         "score":7.8,  "score_orig":5,  "score_riffles":8.1,  "score_riffle_pools":7.4,  "score_pools":6.8},
	{"common_name":"Beetles",             "family":"Hydrophilidae",     "score":5.1,  "score_orig":5,  "score_riffles":5.5,  "score_riffle_pools":4.5,  "score_pools":3.9},
	{"common_name":"Beetles",             "family":"Clambidae",         "score":null, "score_orig":5,  "score_riffles":null, "score_riffle_pools":null, "score_pools":null },
	{"common_name":"Beetles",             "family":"Scirtidae",         "score":6.5,  "score_orig":5,  "score_riffles":6.9,  "score_riffle_pools":6.2,  "score_pools":5.8},
	{"common_name":"Beetles",             "family":"Dryopidae",         "score":6.5,  "score_orig":5,  "score_riffles":6.5,  "score_riffle_pools":null, "score_pools":null },
	{"common_name":"Beetles",             "family":"Elmidae",           "score":6.4,  "score_orig":5,  "score_riffles":6.5,  "score_riffle_pools":6.1,  "score_pools":6.5},
	{"common_name":"Beetles",             "family":"Chrysomelidae *",   "score":4.2,  "score_orig":5,  "score_riffles":4.9,  "score_riffle_pools":1.1,  "score_pools":4.1},
	{"common_name":"Beetles",             "family":"Curculionidae *",   "score":4,    "score_orig":5,  "score_riffles":4.7,  "score_riffle_pools":3.1,  "score_pools":2.9},
	{"common_name":"Alderflies",          "family":"Sialidae",          "score":4.5,  "score_orig":4,  "score_riffles":4.7,  "score_riffle_pools":4.7,  "score_pools":4.3},
	{"common_name":"Caddisflies",         "family":"Rhyacophilidae",    "score":8.3,  "score_orig":7,  "score_riffles":8.2,  "score_riffle_pools":8.6,  "score_pools":9.6},
	{"common_name":"Caddisflies",         "family":"Philopotamidae",    "score":10.6, "score_orig":8,  "score_riffles":10.7, "score_riffle_pools":9.8,  "score_pools":null },
	{"common_name":"Caddisflies",         "family":"Polycentropidae",   "score":8.6,  "score_orig":7,  "score_riffles":8.6,  "score_riffle_pools":8.4,  "score_pools":8.7},
	{"common_name":"Caddisflies",         "family":"Psychomyiidae",     "score":6.9,  "score_orig":8,  "score_riffles":6.4,  "score_riffle_pools":7.4,  "score_pools":8},
	{"common_name":"Caddisflies",         "family":"Hydropsychidae",    "score":6.6,  "score_orig":5,  "score_riffles":6.6,  "score_riffle_pools":6.5,  "score_pools":7.2},
	{"common_name":"Caddisflies",         "family":"Hydroptilidae",     "score":6.7,  "score_orig":6,  "score_riffles":6.7,  "score_riffle_pools":6.8,  "score_pools":6.5},
	{"common_name":"Caddisflies",         "family":"Phryganeidae",      "score":7,    "score_orig":10, "score_riffles":6.6,  "score_riffle_pools":5.4,  "score_pools":8},
	{"common_name":"Caddisflies",         "family":"Limnephilidae",     "score":6.9,  "score_orig":7,  "score_riffles":7.1,  "score_riffle_pools":6.5,  "score_pools":6.6},
	{"common_name":"Caddisflies",         "family":"Molannidae",        "score":8.9,  "score_orig":10, "score_riffles":7.8,  "score_riffle_pools":8.1,  "score_pools":10},
	{"common_name":"Caddisflies",         "family":"Beraeidae",         "score":9,    "score_orig":10, "score_riffles":8.3,  "score_riffle_pools":7.8,  "score_pools":10},
	{"common_name":"Caddisflies",         "family":"Odontoceridae",     "score":10.9, "score_orig":10, "score_riffles":10.8, "score_riffle_pools":11.4, "score_pools":11.7},
	{"common_name":"Caddisflies",         "family":"Leptoceridae",      "score":7.8,  "score_orig":10, "score_riffles":7.8,  "score_riffle_pools":7.7,  "score_pools":8.1},
	{"common_name":"Caddisflies",         "family":"Goeridae",          "score":9.9,  "score_orig":10, "score_riffles":9.8,  "score_riffle_pools":9.6,  "score_pools":12.4},
	{"common_name":"Caddisflies",         "family":"Lepidostomatidae",  "score":10.4, "score_orig":10, "score_riffles":10.3, "score_riffle_pools":10.7, "score_pools":11.6},
	{"common_name":"Caddisflies",         "family":"Brachycentridae",   "score":9.4,  "score_orig":10, "score_riffles":9.3,  "score_riffle_pools":9.7,  "score_pools":11},
	{"common_name":"Caddisflies",         "family":"Sericostomatidae",  "score":9.2,  "score_orig":10, "score_riffles":9.1,  "score_riffle_pools":9.3,  "score_pools":10.3},
	{"common_name":"True flies",          "family":"Tipulidae",         "score":5.5,  "score_orig":5,  "score_riffles":5.6,  "score_riffle_pools":5,    "score_pools":5.1},
	{"common_name":"True flies",          "family":"Chironomidae",      "score":3.7,  "score_orig":2,  "score_riffles":4.1,  "score_riffle_pools":3.4,  "score_pools":2.8},
	{"common_name":"True flies",          "family":"Simuliidae",        "score":5.8,  "score_orig":5,  "score_riffles":5.9,  "score_riffle_pools":5.1,  "score_pools":5.5}
];

export default scoresBmwp;