export interface IScoreBMWP {
    // family:            string,
    common_name:       string,
    score_orig:        number,
    score_rev:         number | null,
    score_riffle:      number | null,
    score_riffle_pool: number | null,
    score_pool:        number | null,
}

export const scoresBmwp: Map<string, IScoreBMWP> = new Map([
	["Planariidae",           { "common_name":" Flatworms",           "score_orig":5,  "score_rev":4.2,  "score_riffle":4.5,  "score_riffle_pool":4.1,  "score_pool":3.7  }],
	["Dendrocoelidae",        { "common_name":" Flatworms",           "score_orig":5,  "score_rev":3.1,  "score_riffle":2.3,  "score_riffle_pool":4.1,  "score_pool":3.1  }],
	["Neritidae",             { "common_name":" Snails",              "score_orig":6,  "score_rev":7.5,  "score_riffle":6.7,  "score_riffle_pool":8.1,  "score_pool":9.3  }],
	["Viviparidae",           { "common_name":" Snails",              "score_orig":6,  "score_rev":6.3,  "score_riffle":2.1,  "score_riffle_pool":4.7,  "score_pool":7.1  }],
	["Valvatidae",            { "common_name":" Snails",              "score_orig":3,  "score_rev":2.8,  "score_riffle":2.5,  "score_riffle_pool":2.5,  "score_pool":3.2  }],
	["Hydrobiidae",           { "common_name":" Snails",              "score_orig":3,  "score_rev":3.9,  "score_riffle":4.1,  "score_riffle_pool":3.9,  "score_pool":3.7  }],
	["Lymnaeidae",            { "common_name":" Snails",              "score_orig":3,  "score_rev":3,    "score_riffle":3.2,  "score_riffle_pool":3.1,  "score_pool":2.8  }],
	["Physidae",              { "common_name":" Snails",              "score_orig":3,  "score_rev":1.8,  "score_riffle":0.9,  "score_riffle_pool":1.5,  "score_pool":2.8  }],
	["Planorbidae",           { "common_name":" Snails",              "score_orig":3,  "score_rev":2.9,  "score_riffle":2.6,  "score_riffle_pool":2.9,  "score_pool":3.1  }],
	["Ancylidae",             { "common_name":" Limpets and Mussels", "score_orig":6,  "score_rev":5.6,  "score_riffle":5.5,  "score_riffle_pool":5.5,  "score_pool":6.2  }],
	["Unionidae",             { "common_name":" Limpets and Mussels", "score_orig":6,  "score_rev":5.2,  "score_riffle":4.7,  "score_riffle_pool":4.8,  "score_pool":5.5  }],
	["Sphaeriidae",           { "common_name":" Limpets and Mussels", "score_orig":3,  "score_rev":3.6,  "score_riffle":3.7,  "score_riffle_pool":3.7,  "score_pool":3.4  }],
	["Oligochaeta",           { "common_name":" Worms",               "score_orig":1,  "score_rev":3.5,  "score_riffle":3.9,  "score_riffle_pool":3.2,  "score_pool":2.5  }],
	["Piscicolidae",          { "common_name":" Leeches",             "score_orig":4,  "score_rev":5,    "score_riffle":4.5,  "score_riffle_pool":5.4,  "score_pool":5.2  }],
	["Glossiphoniidae",       { "common_name":" Leeches",             "score_orig":3,  "score_rev":3.1,  "score_riffle":3,    "score_riffle_pool":3.3,  "score_pool":2.9  }],
	["Hirudididae",           { "common_name":" Leeches",             "score_orig":3,  "score_rev":0,    "score_riffle":0.3,  "score_riffle_pool":-0.3, "score_pool":null }],
	["Erpobdellidae",         { "common_name":" Leeches",             "score_orig":3,  "score_rev":2.8,  "score_riffle":2.8,  "score_riffle_pool":2.8,  "score_pool":2.6  }],
	["Asellidae",             { "common_name":" Crustaceans",         "score_orig":3,  "score_rev":2.1,  "score_riffle":1.5,  "score_riffle_pool":2.4,  "score_pool":2.7  }],
	["Corophiidae",           { "common_name":" Crustaceans",         "score_orig":6,  "score_rev":6.1,  "score_riffle":5.4,  "score_riffle_pool":5.1,  "score_pool":6.5  }],
	["Gammaridae",            { "common_name":" Crustaceans",         "score_orig":6,  "score_rev":4.5,  "score_riffle":4.7,  "score_riffle_pool":4.3,  "score_pool":4.3  }],
	["Astacidae",             { "common_name":" Crustaceans",         "score_orig":8,  "score_rev":9,    "score_riffle":8.8,  "score_riffle_pool":9,    "score_pool":11.2 }],
	["Siphlonuridae",         { "common_name":" Mayflies",            "score_orig":10, "score_rev":11,   "score_riffle":11,   "score_riffle_pool":null, "score_pool":null }],
	["Baetidae",              { "common_name":" Mayflies",            "score_orig":4,  "score_rev":5.3,  "score_riffle":5.5,  "score_riffle_pool":4.8,  "score_pool":5.1  }],
	["Heptageniidae",         { "common_name":" Mayflies",            "score_orig":10, "score_rev":9.8,  "score_riffle":9.7,  "score_riffle_pool":10.7, "score_pool":13   }],
	["Leptophlebiidae",       { "common_name":" Mayflies",            "score_orig":10, "score_rev":8.9,  "score_riffle":8.7,  "score_riffle_pool":8.9,  "score_pool":9.9  }],
	["Ephemerellidae",        { "common_name":" Mayflies",            "score_orig":10, "score_rev":7.7,  "score_riffle":7.6,  "score_riffle_pool":8.1,  "score_pool":9.3  }],
	["Potamanthidae",         { "common_name":" Mayflies",            "score_orig":10, "score_rev":7.6,  "score_riffle":7.6,  "score_riffle_pool":null, "score_pool":null }],
	["Ephemeridae",           { "common_name":" Mayflies",            "score_orig":10, "score_rev":9.3,  "score_riffle":9,    "score_riffle_pool":9.2,  "score_pool":11   }],
	["Caenidae",              { "common_name":" Mayflies",            "score_orig":7,  "score_rev":7.1,  "score_riffle":7.2,  "score_riffle_pool":7.3,  "score_pool":6.4  }],
	["Taeniopterygidae",      { "common_name":" Stoneflies",          "score_orig":10, "score_rev":10.8, "score_riffle":10.7, "score_riffle_pool":12.1, "score_pool":null }],
	["Nemouridae",            { "common_name":" Stoneflies",          "score_orig":7,  "score_rev":9.1,  "score_riffle":9.2,  "score_riffle_pool":8.5,  "score_pool":8.8  }],
	["Leuctridae",            { "common_name":" Stoneflies",          "score_orig":10, "score_rev":9.9,  "score_riffle":9.8,  "score_riffle_pool":10.4, "score_pool":11.2 }],
	["Capniidae",             { "common_name":" Stoneflies",          "score_orig":10, "score_rev":10,   "score_riffle":10.1, "score_riffle_pool":null, "score_pool":null }],
	["Perlodidae",            { "common_name":" Stoneflies",          "score_orig":10, "score_rev":10.7, "score_riffle":10.8, "score_riffle_pool":10.7, "score_pool":10.9 }],
	["Perlidae",              { "common_name":" Stoneflies",          "score_orig":10, "score_rev":12.5, "score_riffle":12.5, "score_riffle_pool":12.2, "score_pool":null }],
	["Chloroperlidae",        { "common_name":" Stoneflies",          "score_orig":10, "score_rev":12.4, "score_riffle":12.5, "score_riffle_pool":12.1, "score_pool":null }],
	["Platycnemidae",         { "common_name":" Damselflies",         "score_orig":6,  "score_rev":5.1,  "score_riffle":3.6,  "score_riffle_pool":5.4,  "score_pool":5.7  }],
	["Coenagriidae",          { "common_name":" Damselflies",         "score_orig":6,  "score_rev":3.5,  "score_riffle":2.6,  "score_riffle_pool":3.3,  "score_pool":3.8  }],
	["Lestidae",              { "common_name":" Damselflies",         "score_orig":8,  "score_rev":5.4,  "score_riffle":null, "score_riffle_pool":null, "score_pool":5.4  }],
	["Calopterygidae",        { "common_name":" Damselflies",         "score_orig":8,  "score_rev":6.4,  "score_riffle":6,    "score_riffle_pool":6.1,  "score_pool":7.6  }],
	["Gomphidae",             { "common_name":" Dragonflies",         "score_orig":8,  "score_rev":null, "score_riffle":null, "score_riffle_pool":null, "score_pool":null }],
	["Cordulegasteridae",     { "common_name":" Dragonflies",         "score_orig":8,  "score_rev":8.6,  "score_riffle":9.5,  "score_riffle_pool":6.5,  "score_pool":7.6  }],
	["Aeshnidae",             { "common_name":" Dragonflies",         "score_orig":8,  "score_rev":6.1,  "score_riffle":7,    "score_riffle_pool":6.9,  "score_pool":5.7  }],
	["Corduliidae",           { "common_name":" Dragonflies",         "score_orig":8,  "score_rev":null, "score_riffle":null, "score_riffle_pool":null, "score_pool":null }],
	["Libellulidae",          { "common_name":" Dragonflies",         "score_orig":8,  "score_rev":5,    "score_riffle":null, "score_riffle_pool":null, "score_pool":5    }],
	// ["Mesoveliidae *",    { "common_name":" Bugs",                "score_orig":5,  "score_rev":4.7,  "score_riffle":4.9,  "score_riffle_pool":4,    "score_pool":5.1}],
	["Hydrometridae",         { "common_name":" Bugs",                "score_orig":5,  "score_rev":5.3,  "score_riffle":5,    "score_riffle_pool":6.2,  "score_pool":4.9  }],
	["Gerridae",              { "common_name":" Bugs",                "score_orig":5,  "score_rev":4.7,  "score_riffle":4.5,  "score_riffle_pool":5,    "score_pool":4.7  }],
	["Nepidae",               { "common_name":" Bugs",                "score_orig":5,  "score_rev":4.3,  "score_riffle":4.1,  "score_riffle_pool":4.2,  "score_pool":4.5  }],
	["Naucoridae",            { "common_name":" Bugs",                "score_orig":5,  "score_rev":4.3,  "score_riffle":null, "score_riffle_pool":null, "score_pool":4.3  }],
	["Aphelocheiridae",       { "common_name":" Bugs",                "score_orig":10, "score_rev":8.9,  "score_riffle":8.4,  "score_riffle_pool":9.5,  "score_pool":11.7 }],
	["Notonectidae",          { "common_name":" Bugs",                "score_orig":5,  "score_rev":3.8,  "score_riffle":1.8,  "score_riffle_pool":3.4,  "score_pool":4.4  }],
	["Pleidae",               { "common_name":" Bugs",                "score_orig":5,  "score_rev":3.9,  "score_riffle":null, "score_riffle_pool":null, "score_pool":3.9  }],
	["Corixidae",             { "common_name":" Bugs",                "score_orig":5,  "score_rev":3.7,  "score_riffle":3.6,  "score_riffle_pool":3.5,  "score_pool":3.9  }],
	["Haliplidae",            { "common_name":" Beetles",             "score_orig":5,  "score_rev":4,    "score_riffle":3.7,  "score_riffle_pool":4.2,  "score_pool":4.3  }],
	["Hygrobiidae",           { "common_name":" Beetles",             "score_orig":5,  "score_rev":2.6,  "score_riffle":5.6,  "score_riffle_pool":-0.8, "score_pool":2.6  }],
	["Dytiscidae",            { "common_name":" Beetles",             "score_orig":5,  "score_rev":4.8,  "score_riffle":5.2,  "score_riffle_pool":4.3,  "score_pool":4.2  }],
	["Gyrinidae",             { "common_name":" Beetles",             "score_orig":5,  "score_rev":7.8,  "score_riffle":8.1,  "score_riffle_pool":7.4,  "score_pool":6.8  }],
	["Hydrophilidae",         { "common_name":" Beetles",             "score_orig":5,  "score_rev":5.1,  "score_riffle":5.5,  "score_riffle_pool":4.5,  "score_pool":3.9  }],
	["Clambidae",             { "common_name":" Beetles",             "score_orig":5,  "score_rev":null, "score_riffle":null, "score_riffle_pool":null, "score_pool":null }],
	["Scirtidae",             { "common_name":" Beetles",             "score_orig":5,  "score_rev":6.5,  "score_riffle":6.9,  "score_riffle_pool":6.2,  "score_pool":5.8  }],
	["Dryopidae",             { "common_name":" Beetles",             "score_orig":5,  "score_rev":6.5,  "score_riffle":6.5,  "score_riffle_pool":null, "score_pool":null }],
	["Elmidae",               { "common_name":" Beetles",             "score_orig":5,  "score_rev":6.4,  "score_riffle":6.5,  "score_riffle_pool":6.1,  "score_pool":6.5  }],
	// ["Chrysomelidae *",   { "common_name":" Beetles",             "score_orig":5,  "score_rev":4.2,  "score_riffle":4.9,  "score_riffle_pool":1.1,  "score_pool":4.1}],
	// ["Curculionidae *",   { "common_name":" Beetles",             "score_orig":5,  "score_rev":4,    "score_riffle":4.7,  "score_riffle_pool":3.1,  "score_pool":2.9}],
	["Sialidae",              { "common_name":" Alderflies",          "score_orig":4,  "score_rev":4.5,  "score_riffle":4.7,  "score_riffle_pool":4.7,  "score_pool":4.3  }],
	["Rhyacophilidae",        { "common_name":" Caddisflies",         "score_orig":7,  "score_rev":8.3,  "score_riffle":8.2,  "score_riffle_pool":8.6,  "score_pool":9.6  }],
	["Philopotamidae",        { "common_name":" Caddisflies",         "score_orig":8,  "score_rev":10.6, "score_riffle":10.7, "score_riffle_pool":9.8,  "score_pool":null }],
	["Polycentropidae",       { "common_name":" Caddisflies",         "score_orig":7,  "score_rev":8.6,  "score_riffle":8.6,  "score_riffle_pool":8.4,  "score_pool":8.7  }],
	["Psychomyiidae",         { "common_name":" Caddisflies",         "score_orig":8,  "score_rev":6.9,  "score_riffle":6.4,  "score_riffle_pool":7.4,  "score_pool":8    }],
	["Hydropsychidae",        { "common_name":" Caddisflies",         "score_orig":5,  "score_rev":6.6,  "score_riffle":6.6,  "score_riffle_pool":6.5,  "score_pool":7.2  }],
	["Hydroptilidae",         { "common_name":" Caddisflies",         "score_orig":6,  "score_rev":6.7,  "score_riffle":6.7,  "score_riffle_pool":6.8,  "score_pool":6.5  }],
	["Phryganeidae",          { "common_name":" Caddisflies",         "score_orig":10, "score_rev":7,    "score_riffle":6.6,  "score_riffle_pool":5.4,  "score_pool":8    }],
	["Limnephilidae",         { "common_name":" Caddisflies",         "score_orig":7,  "score_rev":6.9,  "score_riffle":7.1,  "score_riffle_pool":6.5,  "score_pool":6.6  }],
	["Molannidae",            { "common_name":" Caddisflies",         "score_orig":10, "score_rev":8.9,  "score_riffle":7.8,  "score_riffle_pool":8.1,  "score_pool":10   }],
	["Beraeidae",             { "common_name":" Caddisflies",         "score_orig":10, "score_rev":9,    "score_riffle":8.3,  "score_riffle_pool":7.8,  "score_pool":10   }],
	["Odontoceridae",         { "common_name":" Caddisflies",         "score_orig":10, "score_rev":10.9, "score_riffle":10.8, "score_riffle_pool":11.4, "score_pool":11.7 }],
	["Leptoceridae",          { "common_name":" Caddisflies",         "score_orig":10, "score_rev":7.8,  "score_riffle":7.8,  "score_riffle_pool":7.7,  "score_pool":8.1  }],
	["Goeridae",              { "common_name":" Caddisflies",         "score_orig":10, "score_rev":9.9,  "score_riffle":9.8,  "score_riffle_pool":9.6,  "score_pool":12.4 }],
	["Lepidostomatidae",      { "common_name":" Caddisflies",         "score_orig":10, "score_rev":10.4, "score_riffle":10.3, "score_riffle_pool":10.7, "score_pool":11.6 }],
	["Brachycentridae",       { "common_name":" Caddisflies",         "score_orig":10, "score_rev":9.4,  "score_riffle":9.3,  "score_riffle_pool":9.7,  "score_pool":11   }],
	["Sericostomatidae",      { "common_name":" Caddisflies",         "score_orig":10, "score_rev":9.2,  "score_riffle":9.1,  "score_riffle_pool":9.3,  "score_pool":10.3 }],
	["Tipulidae",             { "common_name":" True flies",          "score_orig":5,  "score_rev":5.5,  "score_riffle":5.6,  "score_riffle_pool":5,    "score_pool":5.1  }],
	["Chironomidae",          { "common_name":" True flies",          "score_orig":2,  "score_rev":3.7,  "score_riffle":4.1,  "score_riffle_pool":3.4,  "score_pool":2.8  }],
	["Simuliidae",            { "common_name":" True flies",          "score_orig":5,  "score_rev":5.8,  "score_riffle":5.9,  "score_riffle_pool":5.1,  "score_pool":5.5  }],
]);

// Source: http://www.cies.staffs.ac.uk/bmwptabl.htm
//
//  * These families are now excluded from the list used for the calculation of the score.
//    A blank indicates that there were insufficient records for the calculations.
//
// The Revised BMWP Scores are based on the analysis of frequency of occurrence of the families
// recorded in approximately 17,000 samples.
//
// The Habitat Specific Scores are based on the following substrate compositions:
// Riffles: >= 70% boulders and pebbles    Pool: >= 70% sand and silt    Riffle/Pool: the remainder

export interface IScoreWHPT {
    // family:      string,
    score_presence: number,
    scores:         number[],
}

export const scoresWhpt: Map<string, IScoreWHPT> = new Map([
	["Planariidae",       { "score_presence": 4.9,  "scores": [4.7,  5.4,  5.4,  5.4 ] }],
	["Dugesiidae",        { "score_presence": 2.9,  "scores": [2.8,  3.1,  3.1,  3.1 ] }],
	["Dendrocoelidae",    { "score_presence": 3,    "scores": [3,    2.6,  2.6,  2.6 ] }],
	["Neritidae",         { "score_presence": 6.4,  "scores": [6.4,  6.5,  6.9,  6.9 ] }],
	["Viviparidae",       { "score_presence": 5.7,  "scores": [5.2,  6.7,  6.7,  6.7 ] }],
	["Valvatidae",        { "score_presence": 3.2,  "scores": [3.3,  3.1,  2.7,  2.7 ] }],
	["Hydrobiidae",       { "score_presence": 4.2,  "scores": [4.1,  4.2,  4.6,  3.7 ] }],
	["Bithyniidae",       { "score_presence": 3.7,  "scores": [3.6,  3.8,  3.3,  3.3 ] }],
	["Physidae",          { "score_presence": 2.4,  "scores": [2.7,  2,    0.4,  0.4 ] }],
	["Lymnaeidae",        { "score_presence": 3.3,  "scores": [3.6,  2.5,  1.2,  1.2 ] }],
	["Planorbidae",       { "score_presence": 3.1,  "scores": [3.2,  3,    2.4,  2.4 ] }],
	["Ancylidae",         { "score_presence": 5.7,  "scores": [5.8,  5.5,  5.5,  5.5 ] }],
	["Acroloxidae",       { "score_presence": 3.6,  "scores": [3.6,  3.8,  3.8,  3.8 ] }],
	["Unionidae",         { "score_presence": 5.3,  "scores": [5.2,  6.8,  6.8,  6.8 ] }],
	["Sphaeriidae",       { "score_presence": 3.9,  "scores": [4.4,  3.5,  3.4,  2.3 ] }],
	["Dreissenidae",      { "score_presence": 3.7,  "scores": [3.7,  3.7,  3.7,  3.7 ] }],
	["Oligochaeta",       { "score_presence": 2.7,  "scores": [3.6,  2.3,  1.4,  -0.6] }],
	["Piscicolidae",      { "score_presence": 5.2,  "scores": [5.2,  4.9,  4.9,  4.9 ] }],
	["Glossiphoniidae",   { "score_presence": 3.2,  "scores": [3.4,  2.5,  0.8,  0.8 ] }],
	["Hirudinidae",       { "score_presence": -0.8, "scores": [-0.8, -0.8, -0.8, -0.8] }],
	["Erpobdellidae",     { "score_presence": 3.1,  "scores": [3.6,  2,    -0.8, -0.8] }],
	["Astacidae",         { "score_presence": 7.9,  "scores": [7.9,  7.9,  7.9,  7.9 ] }],
	["Asellidae",         { "score_presence": 2.8,  "scores": [4,    2.3,  0.8,  -1.6] }],
	["Corophiidae",       { "score_presence": 5.8,  "scores": [5.7,  5.8,  5.8,  5.8 ] }],
	["Crangonyctidae",    { "score_presence": 3.9,  "scores": [3.8,  4,    3.6,  3.6 ] }],
	["Gammaridae",        { "score_presence": 4.4,  "scores": [4.2,  4.5,  4.6,  3.9 ] }],
	["Niphargidae",       { "score_presence": 6.3,  "scores": [6.3,  6.3,  6.3,  6.3 ] }],
	["Siphlonuridae",     { "score_presence": 11.5, "scores": [11.3, 12.2, 12.2, 12.2] }],
	["Baetidae",          { "score_presence": 5.5,  "scores": [3.6,  5.9,  7.2,  7.5 ] }],
	["Heptageniidae",     { "score_presence": 9.7,  "scores": [8.5,  10.3, 11.1, 11.1] }],
	["Leptophlebiidae",   { "score_presence": 8.8,  "scores": [8.8,  9.1,  9.2,  9.2 ] }],
	["Potamanthidae",     { "score_presence": 10,   "scores": [9.8,  10.4, 10.4, 10.4] }],
	["Ephemeridae",       { "score_presence": 8.4,  "scores": [8.3,  8.8,  9.4,  9.4 ] }],
	["Ephemerellidae",    { "score_presence": 8.2,  "scores": [7.9,  8.5,  9,    9   ] }],
	["Caenidae",          { "score_presence": 6.5,  "scores": [6.5,  6.5,  6.5,  6.5 ] }],
	["Taeniopterygidae",  { "score_presence": 11.3, "scores": [11,   11.9, 12.1, 12.1] }],
	["Nemouridae",        { "score_presence": 9.3,  "scores": [8.7,  10.7, 10.7, 10.7] }],
	["Leuctridae",        { "score_presence": 10,   "scores": [9.3,  10.6, 10.6, 10.6] }],
	["Capniidae",         { "score_presence": 9.6,  "scores": [9.7,  9.4,  9.4,  9.4 ] }],
	["Perlodidae",        { "score_presence": 10.8, "scores": [10.5, 11.5, 11.5, 11.5] }],
	["Perlidae",          { "score_presence": 12.7, "scores": [12.6, 13,   13,   13  ] }],
	["Chloroperlidae",    { "score_presence": 11.6, "scores": [11.4, 12.2, 12.2, 12.2] }],
	["Platycnemididae",   { "score_presence": 6,    "scores": [6,    6,    6,    6   ] }],
	["Coenagriidae",      { "score_presence": 3.5,  "scores": [3.4,  3.8,  3.8,  3.8 ] }],
	["Calopterygidae",    { "score_presence": 6,    "scores": [5.9,  6.2,  6.2,  6.2 ] }],
	["Cordulegasteridae", { "score_presence": 9.8,  "scores": [9.8,  9.8,  9.8,  9.8 ] }],
	["Aeshnidae",         { "score_presence": 4.7,  "scores": [4.7,  4.7,  4.7,  4.7 ] }],
	["Libellulidae",      { "score_presence": 4.1,  "scores": [4.1,  4.1,  4.1,  4.1 ] }],
	["Mesoveliidae",      { "score_presence": 4.7,  "scores": [4.7,  4.7,  4.7,  4.7 ] }],
	["Hydrometridae",     { "score_presence": 4.3,  "scores": [4.3,  4.3,  4.3,  4.3 ] }],
	["Veliidae",          { "score_presence": 4.5,  "scores": [4.5,  3.9,  3.9,  3.9 ] }],
	["Gerridae",          { "score_presence": 5.2,  "scores": [5.2,  5.5,  5.5,  5.5 ] }],
	["Nepidae",           { "score_presence": 2.9,  "scores": [2.9,  2.9,  2.9,  2.9 ] }],
	["Naucoridae",        { "score_presence": 3.7,  "scores": [3.7,  3.7,  3.7,  3.7 ] }],
	["Aphelocheiridae",   { "score_presence": 8.5,  "scores": [8.6,  8.5,  8,    8   ] }],
	["Notonectidae",      { "score_presence": 3.4,  "scores": [3.4,  3.9,  3.9,  3.9 ] }],
	["Pleidae",           { "score_presence": 3.3,  "scores": [3.3,  3.3,  3.3,  3.3 ] }],
	["Corixidae",         { "score_presence": 3.8,  "scores": [3.7,  3.9,  3.7,  3.7 ] }],
	["Haliplidae",        { "score_presence": 3.6,  "scores": [3.6,  3.4,  3.4,  3.4 ] }],
	["Hygrobiidae",       { "score_presence": 3.8,  "scores": [3.8,  3.8,  3.8,  3.8 ] }],
	["Noteridae",         { "score_presence": 3.2,  "scores": [3.2,  3.2,  3.2,  3.2 ] }],
	["Dytiscidae",        { "score_presence": 4.5,  "scores": [4.5,  4.8,  4.8,  4.8 ] }],
	["Gyrinidae",         { "score_presence": 8.2,  "scores": [8.1,  9,    9,    9   ] }],
	["Hydrophilidae",     { "score_presence": 6.2,  "scores": [5.8,  8.8,  8.8,  8.8 ] }],
	["Hydraenidae",       { "score_presence": 8.9,  "scores": [8.5,  10.5, 10.5, 10.5] }],
	["Scirtidae",         { "score_presence": 6.9,  "scores": [6.9,  6.8,  6.8,  6.8 ] }],
	["Dryopidae",         { "score_presence": 6,    "scores": [6,    6,    6,    6   ] }],
	["Elmidae",           { "score_presence": 6.6,  "scores": [5.3,  7.4,  8.3,  8.3 ] }],
	["Sialidae",          { "score_presence": 4.3,  "scores": [4.2,  4.4,  4.4,  4.4 ] }],
	["Sisyridae",         { "score_presence": 5.7,  "scores": [5.7,  5.7,  5.7,  5.7 ] }],
	["Rhyacophilidae",    { "score_presence": 8.4,  "scores": [8.1,  9.2,  8.3,  8.3 ] }],
	["Glossosomatidae",   { "score_presence": 7.7,  "scores": [7.8,  7.6,  7.2,  7.2 ] }],
	["Hydroptilidae",     { "score_presence": 6.2,  "scores": [6.1,  6.5,  6.8,  6.8 ] }],
	["Philopotamidae",    { "score_presence": 11.2, "scores": [11.2, 11.1, 11.1, 11.1] }],
	["Psychomyiidae",     { "score_presence": 5.8,  "scores": [5.8,  5.7,  5.7,  5.7 ] }],
	["Polycentropodidae", { "score_presence": 8.1,  "scores": [8.2,  8.1,  8.1,  8.1 ] }],
	["Hydropsychidae",    { "score_presence": 6.6,  "scores": [5.8,  7.2,  7.4,  7.4 ] }],
	["Phryganeidae",      { "score_presence": 5.5,  "scores": [5.5,  5.5,  5.5,  5.5 ] }],
	["Brachycentridae",   { "score_presence": 9.5,  "scores": [9.6,  9.5,  8.9,  8.9 ] }],
	["Lepidostomatidae",  { "score_presence": 10.1, "scores": [9.9,  10.3, 10.2, 10.2] }],
	["Limnephilidae",     { "score_presence": 6.2,  "scores": [5.9,  6.9,  6.9,  6.9 ] }],
	["Goeridae",          { "score_presence": 8.8,  "scores": [8.8,  8.8,  9.4,  9.4 ] }],
	["Beraeidae",         { "score_presence": 8.7,  "scores": [8.8,  7.3,  7.3,  7.3 ] }],
	["Sericostomatidae",  { "score_presence": 9.1,  "scores": [8.9,  9.4,  9.5,  9.5 ] }],
	["Odontoceridae",     { "score_presence": 11,   "scores": [11.1, 10.3, 10.3, 10.3] }],
	["Molannidae",        { "score_presence": 6.6,  "scores": [6.5,  7.6,  7.6,  7.6 ] }],
	["Leptoceridae",      { "score_presence": 6.7,  "scores": [6.7,  6.9,  7.1,  7.1 ] }],
	["Tipulidae",         { "score_presence": 5.9,  "scores": [5.4,  6.9,  6.9,  7.1 ] }],
	["Psychodidae",       { "score_presence": 4.4,  "scores": [4.5,  3,    3,    3   ] }],
	["Ptychopteridae",    { "score_presence": 6.4,  "scores": [6.4,  6.4,  6.4,  6.4 ] }],
	["Dixidae",           { "score_presence": 7,    "scores": [7,    7,    7,    7   ] }],
	["Chaoboridae",       { "score_presence": 3,    "scores": [3,    3,    3,    3   ] }],
	["Culicidae",         { "score_presence": 2,    "scores": [2,    1.9,  1.9,  1.9 ] }],
	["Ceratopogonidae",   { "score_presence": 5.5,  "scores": [5.4,  5.5,  5.5,  5.5 ] }],
	["Simuliidae",        { "score_presence": 5.8,  "scores": [5.5,  6.1,  5.8,  3.9 ] }],
	["Chironomidae",      { "score_presence": 1.1,  "scores": [1.2,  1.3,  -0.9, -0.9] }],
	["Stratiomyidae",     { "score_presence": 3.6,  "scores": [3.6,  3.6,  3.6,  3.6 ] }],
	["Rhagionidae",       { "score_presence": 9.6,  "scores": [9.6,  9.6,  9.6,  9.6 ] }],
	["Tabanidae",         { "score_presence": 7.1,  "scores": [7.1,  7.3,  7.3,  7.3 ] }],
	["Athericidae",       { "score_presence": 9.3,  "scores": [9.3,  9.5,  9.5,  9.5 ] }],
	["Empididae",         { "score_presence": 7.1,  "scores": [7,    7.6,  7.6,  7.6 ] }],
	["Dolichopodidae",    { "score_presence": 4.9,  "scores": [4.9,  4.9,  4.9,  4.9 ] }],
	["Syrphidae",         { "score_presence": 1.9,  "scores": [1.9,  1.9,  1.9,  1.9 ] }],
	["Sciomyzidae",       { "score_presence": 3.4,  "scores": [3.4,  3.4,  3.4,  3.4 ] }],
	["Ephydridae",        { "score_presence": 4.4,  "scores": [4.4,  4.4,  4.4,  4.4 ] }],
	["Muscidae",          { "score_presence": 3.9,  "scores": [4,    2.6,  2.6,  2.6 ] }],
]);

// |-------+-----------------------------------------+-----+-------+---------+-------|
// | Group | Fine Sediment Sensitivity Rating (FSSR) | 1–9 | 10–99 | 100–999 | 1000+ |
// |-------+-----------------------------------------+-----+-------+---------+-------|
// | A     | Highly     sensitive                    | 2   | 3     | 4       | 5     |
// | B     | Moderately sensitive                    | 1   | 2     | 3       | 4     |
// | C     | Moderately insensitive                  | 1   | 2     | 3       | 4     |
// | D     | Highly     insensitive                  | 2   | 3     | 4       | 5     |
// |-------+-----------------------------------------+-----+-------+---------+-------|

export const scoresPsiGroups = { //         Log Abundance (1-9, 10-99...)
	'A': { description: 'Highly sensitive',       scores: [2, 3, 4, 5] },
	'B': { description: 'Moderately sensitive',   scores: [1, 2, 3, 4] },
	'C': { description: 'Moderately insensitive', scores: [1, 2, 3, 4] },
	'D': { description: 'Highly insensitive',     scores: [2, 3, 4, 5] },
}

export interface IScorePsiFam {
    // family (+ Oligochaeta):            string,
	class_order:          string,
	suborder_superfamily: string,
	fssr:                 string,
}

export const scoresPsiFamily: Map<string, IScorePsiFam> = new Map([
	["Spongillidae",      { "class_order":"Porifera",      "suborder_superfamily":"",                 "fssr":"B"}],
	["Planariidae",       { "class_order":"Tricladida",    "suborder_superfamily":"",                 "fssr":"D"}],
	["Dugesiidae",        { "class_order":"Tricladida",    "suborder_superfamily":"",                 "fssr":"D"}],
	["Dendrocoelidae",    { "class_order":"Tricladida",    "suborder_superfamily":"",                 "fssr":"C"}],
	["Neritidae",         { "class_order":"Gastropoda",    "suborder_superfamily":"Prosobranchia",    "fssr":"C"}],
	["Viviparidae",       { "class_order":"Gastropoda",    "suborder_superfamily":"Prosobranchia",    "fssr":"D"}],
	["Valvatidae",        { "class_order":"Gastropoda",    "suborder_superfamily":"Prosobranchia",    "fssr":"C"}],
	["Hydrobiidae",       { "class_order":"Gastropoda",    "suborder_superfamily":"Prosobranchia",    "fssr":"C"}],
	["Bithyniidae",       { "class_order":"Gastropoda",    "suborder_superfamily":"Prosobranchia",    "fssr":"D"}],
	["Physidae",          { "class_order":"Aquatic",       "suborder_superfamily":"Pulmonata",        "fssr":"D"}],
	["Lymnaeidae",        { "class_order":"Aquatic",       "suborder_superfamily":"Pulmonata",        "fssr":"D"}],
	["Planorbidae",       { "class_order":"Aquatic",       "suborder_superfamily":"Pulmonata",        "fssr":"D"}],
	["Margaritiferidae",  { "class_order":"Bivalvia",      "suborder_superfamily":"",                 "fssr":"A"}],
	["Unionidae",         { "class_order":"Bivalvia",      "suborder_superfamily":"",                 "fssr":"D"}],
	["Sphaeriidae",       { "class_order":"Bivalvia",      "suborder_superfamily":"",                 "fssr":"D"}],
	["Oligochaeta",       { "class_order":"Oligochaeta",   "suborder_superfamily":"",                 "fssr":"D"}],
	["Piscicolidae",      { "class_order":"Hirudinea",     "suborder_superfamily":"Rhynchobdella",    "fssr":"B"}],
	["Glossiphoniidae",   { "class_order":"Hirudinea",     "suborder_superfamily":"Rhynchobdella",    "fssr":"C"}],
	["Hirudinidae",       { "class_order":"Hirudinea",     "suborder_superfamily":"Gnathobdellae",    "fssr":"D"}],
	["Erpobdellidae",     { "class_order":"Hirudinea",     "suborder_superfamily":"Gnathobdellae",    "fssr":"C"}],
	["Bathynellidae",     { "class_order":"Bathynellacea", "suborder_superfamily":"",                 "fssr":"B"}],
	["Asellidae",         { "class_order":"Isopoda",       "suborder_superfamily":"",                 "fssr":"D"}],
	["Corophiidae",       { "class_order":"Amphipoda",     "suborder_superfamily":"",                 "fssr":"D"}],
	["Crangonyctidae",    { "class_order":"Amphipoda",     "suborder_superfamily":"",                 "fssr":"D"}],
	["Gammaridae",        { "class_order":"Amphipoda",     "suborder_superfamily":"",                 "fssr":"B"}],
	["Niphargidae",       { "class_order":"Amphipoda",     "suborder_superfamily":"",                 "fssr":"B"}],
	["Siphlonuridae",     { "class_order":"Ephemeroptera", "suborder_superfamily":"Baetoidea",        "fssr":"C"}],
	["Baetidae",          { "class_order":"Ephemeroptera", "suborder_superfamily":"Baetoidea",        "fssr":"A"}],
	["Heptageniidae",     { "class_order":"Ephemeroptera", "suborder_superfamily":"Baetoidea",        "fssr":"A"}],
	["Ameletidae",        { "class_order":"Ephemeroptera", "suborder_superfamily":"Baetoidea",        "fssr":"B"}],
	["Arthropleidae",     { "class_order":"Ephemeroptera", "suborder_superfamily":"Baetoidea",        "fssr":"D"}],
	["Leptophlebiidae",   { "class_order":"Ephemeroptera", "suborder_superfamily":"Leptophlebioidea", "fssr":"B"}],
	["Potamanthidae",     { "class_order":"Ephemeroptera", "suborder_superfamily":"Ephemeroidea",     "fssr":"B"}],
	["Ephemeridae",       { "class_order":"Ephemeroptera", "suborder_superfamily":"Ephemeroidea",     "fssr":"C"}],
	["Ephemerellidae",    { "class_order":"Ephemeroptera", "suborder_superfamily":"Ephemerelloidea",  "fssr":"A"}],
	["Caenidae",          { "class_order":"Ephemeroptera", "suborder_superfamily":"Ephemerelloidea",  "fssr":"D"}],
	["Nemouridae",        { "class_order":"Ephemeroptera", "suborder_superfamily":"Plecoptera",       "fssr":"C"}],
	["Leuctridae",        { "class_order":"Ephemeroptera", "suborder_superfamily":"Plecoptera",       "fssr":"A"}],
	["Capniidae",         { "class_order":"Ephemeroptera", "suborder_superfamily":"Plecoptera",       "fssr":"A"}],
	["Perlodidae",        { "class_order":"Ephemeroptera", "suborder_superfamily":"Setipalpia",       "fssr":"A"}],
	["Perlidae",          { "class_order":"Ephemeroptera", "suborder_superfamily":"Setipalpia",       "fssr":"A"}],
	["Chloroperlidae",    { "class_order":"Ephemeroptera", "suborder_superfamily":"Setipalpia",       "fssr":"A"}],
	["Platycnemididae",   { "class_order":"Odonata",       "suborder_superfamily":"Zygoptera",        "fssr":"D"}],
	["Calopterygidae",    { "class_order":"Odonata",       "suborder_superfamily":"Coenagrionidae",   "fssr":"C"}],
	["Gomphidae",         { "class_order":"Odonata",       "suborder_superfamily":"Anisoptera",       "fssr":"D"}],
	["Cordulegastridae",  { "class_order":"Odonata",       "suborder_superfamily":"Anisoptera",       "fssr":"D"}],
	["Aeshnidae",         { "class_order":"Odonata",       "suborder_superfamily":"Anisoptera",       "fssr":"C"}],
	["Corduliidae",       { "class_order":"Odonata",       "suborder_superfamily":"Anisoptera",       "fssr":"D"}],
	["Libellulidae",      { "class_order":"Odonata",       "suborder_superfamily":"Anisoptera",       "fssr":"C"}],
	["Nepidae",           { "class_order":"Hemiptera",     "suborder_superfamily":"Nepoidea",         "fssr":"D"}],
	["Aphelocheiridae",   { "class_order":"Hemiptera",     "suborder_superfamily":"Naucoroidea",      "fssr":"A"}],
	["Corixidae",         { "class_order":"Hemiptera",     "suborder_superfamily":"Corixoidea",       "fssr":"D"}],
	["Haliplidae",        { "class_order":"Coleoptera",    "suborder_superfamily":"Adephaga",         "fssr":"D"}],
	["Paelobiidae",       { "class_order":"Coleoptera",    "suborder_superfamily":"Adephaga",         "fssr":"D"}],
	["Noteridae",         { "class_order":"Coleoptera",    "suborder_superfamily":"Adephaga",         "fssr":"D"}],
	["Dytiscidae",        { "class_order":"Coleoptera",    "suborder_superfamily":"Adephaga",         "fssr":"D"}],
	["Hydrochidae",       { "class_order":"Coleoptera",    "suborder_superfamily":"Hydrophiloidea",   "fssr":"D"}],
	["Helophoridae",      { "class_order":"Coleoptera",    "suborder_superfamily":"Hydrophiloidea",   "fssr":"D"}],
	["Georissidae",       { "class_order":"Coleoptera",    "suborder_superfamily":"Hydrophiloidea",   "fssr":"D"}],
	["Hydrophilidae",     { "class_order":"Coleoptera",    "suborder_superfamily":"Hydrophiloidea",   "fssr":"D"}],
	["Hydraenidae",       { "class_order":"Coleoptera",    "suborder_superfamily":"Staphylinoidea",   "fssr":"B"}],
	["Scirtidae",         { "class_order":"Coleoptera",    "suborder_superfamily":"Eucinetoidea",     "fssr":"B"}],
	["Dryopidae",         { "class_order":"Coleoptera",    "suborder_superfamily":"Dryopoidea",       "fssr":"D"}],
	["Elmidae",           { "class_order":"Coleoptera",    "suborder_superfamily":"Dryopoidea",       "fssr":"B"}],
	["Limnichidae",       { "class_order":"Coleoptera",    "suborder_superfamily":"Dryopoidea",       "fssr":"D"}],
	["Heteroceridae",     { "class_order":"Coleoptera",    "suborder_superfamily":"Dryopoidea",       "fssr":"D"}],
	["Sialidae",          { "class_order":"Megaloptera",   "suborder_superfamily":"",                 "fssr":"D"}],
	["Osmylidae",         { "class_order":"Neuroptera",    "suborder_superfamily":"",                 "fssr":"B"}],
	["Sisyridae",         { "class_order":"Neuroptera",    "suborder_superfamily":"",                 "fssr":"B"}],
	["Rhyacophilidae",    { "class_order":"Trichoptera",   "suborder_superfamily":"Rhyacophiloidea",  "fssr":"A"}],
	["Glossosomatidae",   { "class_order":"Trichoptera",   "suborder_superfamily":"Rhyacophiloidea",  "fssr":"A"}],
	["Philopotamidae",    { "class_order":"Trichoptera",   "suborder_superfamily":"Hydropsychoidea",  "fssr":"A"}],
	["Psychomyiidae",     { "class_order":"Trichoptera",   "suborder_superfamily":"Hydropsychoidea",  "fssr":"B"}],
	["Ecnomidae",         { "class_order":"Trichoptera",   "suborder_superfamily":"Hydropsychoidea",  "fssr":"C"}],
	["Polycentropodidae", { "class_order":"Trichoptera",   "suborder_superfamily":"Hydropsychoidea",  "fssr":"B"}],
	["Hydropsychidae",    { "class_order":"Trichoptera",   "suborder_superfamily":"Hydropsychoidea",  "fssr":"A"}],
	["Phryganeidae",      { "class_order":"Trichoptera",   "suborder_superfamily":"Limnephiloidea",   "fssr":"D"}],
	["Brachycentridae",   { "class_order":"Trichoptera",   "suborder_superfamily":"Limnephiloidea",   "fssr":"A"}],
	["Lepidostomatidae",  { "class_order":"Trichoptera",   "suborder_superfamily":"Limnephiloidea",   "fssr":"B"}],
	["Limnephilidae",     { "class_order":"Trichoptera",   "suborder_superfamily":"Limnephiloidea",   "fssr":"B"}],
	["Goeridae",          { "class_order":"Trichoptera",   "suborder_superfamily":"Limnephiloidea",   "fssr":"A"}],
	["Beraeidae",         { "class_order":"Trichoptera",   "suborder_superfamily":"Limnephiloidea",   "fssr":"A"}],
	["Sericostomatidae",  { "class_order":"Trichoptera",   "suborder_superfamily":"Limnephiloidea",   "fssr":"B"}],
	["Odontoceridae",     { "class_order":"Trichoptera",   "suborder_superfamily":"Limnephiloidea",   "fssr":"B"}],
	["Molannidae",        { "class_order":"Trichoptera",   "suborder_superfamily":"Limnephiloidea",   "fssr":"C"}],
	["Apataniidae",       { "class_order":"Trichoptera",   "suborder_superfamily":"Limnephiloidea",   "fssr":"A"}],
	["Tipulidae",         { "class_order":"Diptera",       "suborder_superfamily":"Tipuloidea",       "fssr":"B"}],
	["Limoniidae",        { "class_order":"Diptera",       "suborder_superfamily":"Tipuloidea",       "fssr":"B"}],
	["Pediciidae",        { "class_order":"Diptera",       "suborder_superfamily":"Tipuloidea",       "fssr":"B"}],
	["Psychodidae",       { "class_order":"Diptera",       "suborder_superfamily":"Psychodoidea",     "fssr":"D"}],
	["Ptychopteridae",    { "class_order":"Diptera",       "suborder_superfamily":"Psychodoidea",     "fssr":"D"}],
	["Dixidae",           { "class_order":"Diptera",       "suborder_superfamily":"Culicoidea",       "fssr":"B"}],
	["Simuliidae",        { "class_order":"Diptera",       "suborder_superfamily":"Culicoidea",       "fssr":"A"}],
	["Stratiomyidae",     { "class_order":"Diptera",       "suborder_superfamily":"Culicoidea",       "fssr":"C"}],
	["Rhagionidae",       { "class_order":"Diptera",       "suborder_superfamily":"Culicoidea",       "fssr":"D"}],
	["Tabanidae",         { "class_order":"Diptera",       "suborder_superfamily":"Culicoidea",       "fssr":"D"}],
	["Syrphidae",         { "class_order":"Diptera",       "suborder_superfamily":"Culicoidea",       "fssr":"D"}],
]);



export const scoresLifeGroups = { //         Log Abundance (1-9, 10-99...)
	'I':   { description: 'Rapid',             scores: [9, 10, 11, 12] },
	'II':  { description: 'Moderate-fast',     scores: [8, 9 , 10, 11] },
	'III': { description: 'Slow-sluggish',     scores: [7, 7 , 7 , 7 ] },
	'IV':  { description: 'Flowing-standing',  scores: [6, 5 , 4 , 3 ] },
	'V':   { description: 'Standing',          scores: [5, 4 , 3 , 2 ] },
	'VI':  { description: 'Drought_resistant', scores: [4, 3 , 2 , 1 ] },
}

export interface IScoreLifeFam {
    // family:   string,
	major_group: string,
	flow:        string,
}

export const scoresLifeFamily: Map<string, IScoreLifeFam> = new Map([
	["Planariidae",        { "major_group":"Tricladida",    "flow":"IV"  }],
	["Dugesiidae",         { "major_group":"Tricladida",    "flow":"IV"  }],
	["Dendrocoelidae",     { "major_group":"Tricladida",    "flow":"IV"  }],
	["Neritidae",          { "major_group":"Gastropoda",    "flow":"II"  }],
	["Viviparidae",        { "major_group":"Gastropoda",    "flow":"III" }],
	["Valvatidae",         { "major_group":"Gastropoda",    "flow":"IV"  }],
	["Hydrobiidae",        { "major_group":"Gastropoda",    "flow":"IV"  }],
	["Bithyniidae",        { "major_group":"Gastropoda",    "flow":"IV"  }],
	["Lymnaeidae",         { "major_group":"Gastropoda",    "flow":"IV"  }],
	["Physidae",           { "major_group":"Gastropoda",    "flow":"IV"  }],
	["Planorbidae",        { "major_group":"Gastropoda",    "flow":"IV"  }],
	["Ancylidae",          { "major_group":"Gastropoda",    "flow":"II"  }],
	["Acroloxidae",        { "major_group":"Gastropoda",    "flow":"IV"  }],
	["Margaritiferidae",   { "major_group":"Bivalvia",      "flow":"II"  }],
	["Unionidae",          { "major_group":"Bivalvia",      "flow":"IV"  }],
	["Sphaeriidae",        { "major_group":"Bivalvia",      "flow":"IV"  }],
	["Dreissenidae",       { "major_group":"Bivalvia",      "flow":"IV"  }],
	["Piscicolidae",       { "major_group":"Hirudinea",     "flow":"II"  }],
	["Glossiphoniidae",    { "major_group":"Hirudinea",     "flow":"IV"  }],
	["Hirudidae",          { "major_group":"Hirudinea",     "flow":"IV"  }],
	["Erpobdellidae",      { "major_group":"Hirudinea",     "flow":"IV"  }],
	["Agelinidae",         { "major_group":"Araneae",       "flow":"V"   }],
	["Chirocephalidae",    { "major_group":"Anostraca",     "flow":"VI"  }],
	["Triopsidae",         { "major_group":"Notostraca",    "flow":"VI"  }],
	["Mysidae",            { "major_group":"Malacostraca",  "flow":"V"   }],
	["Asellidae",          { "major_group":"Malacostraca",  "flow":"IV"  }],
	["Corophidae",         { "major_group":"Malacostraca",  "flow":"III" }],
	["Gammaridae",         { "major_group":"Malacostraca",  "flow":"II"  }],
	["Crangonycitidae",    { "major_group":"Malacostraca",  "flow":"IV"  }],
	["Talitridae",         { "major_group":"Malacostraca",  "flow":"VI"  }],
	["Astacidae",          { "major_group":"Malacostraca",  "flow":"II"  }],
	["Siphlonuridae",      { "major_group":"Ephemeroptera", "flow":"IV"  }],
	["Baetidae",           { "major_group":"Ephemeroptera", "flow":"II"  }],
	["Heptageniidae",      { "major_group":"Ephemeroptera", "flow":"I"   }],
	["Leptophlebiidae",    { "major_group":"Ephemeroptera", "flow":"II"  }],
	["Ephemerellidae",     { "major_group":"Ephemeroptera", "flow":"II"  }],
	["Potamanthidae",      { "major_group":"Ephemeroptera", "flow":"III" }],
	["Ephemeridae",        { "major_group":"Ephemeroptera", "flow":"II"  }],
	["Caenidae",           { "major_group":"Ephemeroptera", "flow":"IV"  }],
	["Taeniopterigidae",   { "major_group":"Plecoptera",    "flow":"II"  }],
	["Nemouridae",         { "major_group":"Plecoptera",    "flow":"IV"  }],
	["Leuctridae",         { "major_group":"Plecoptera",    "flow":"II"  }],
	["Capniidae",          { "major_group":"Plecoptera",    "flow":"I"   }],
	["Perlodidae",         { "major_group":"Plecoptera",    "flow":"I"   }],
	["Perlidae",           { "major_group":"Plecoptera",    "flow":"I"   }],
	["Chloroperlidae",     { "major_group":"Plecoptera",    "flow":"I"   }],
	["Platycnemididae",    { "major_group":"Odonata",       "flow":"IV"  }],
	["Coenagriidae",       { "major_group":"Odonata",       "flow":"IV"  }],
	["Lestidae",           { "major_group":"Odonata",       "flow":"IV"  }],
	["Agriidae",           { "major_group":"Odonata",       "flow":"III" }],
	["Gomphidae",          { "major_group":"Odonata",       "flow":"II"  }],
	["Cordulegasteridae",  { "major_group":"Odonata",       "flow":"II"  }],
	["Aeshnidae",          { "major_group":"Odonata",       "flow":"IV"  }],
	["Corduliidae",        { "major_group":"Odonata",       "flow":"IV"  }],
	["Libellulidae",       { "major_group":"Odonata",       "flow":"IV"  }],
	["Mesovelidae",        { "major_group":"Hemiptera",     "flow":"V"   }],
	["Hebridae",           { "major_group":"Hemiptera",     "flow":"IV"  }],
	["Hydrometridae",      { "major_group":"Hemiptera",     "flow":"IV"  }],
	["Veliidae",           { "major_group":"Hemiptera",     "flow":"IV"  }],
	["Gerridae",           { "major_group":"Hemiptera",     "flow":"IV"  }],
	["Nepidae",            { "major_group":"Hemiptera",     "flow":"V"   }],
	["Naucoridae",         { "major_group":"Hemiptera",     "flow":"IV"  }],
	["Aphelocheiridae",    { "major_group":"Hemiptera",     "flow":"II"  }],
	["Notonectidae",       { "major_group":"Hemiptera",     "flow":"IV"  }],
	["Pleidae",            { "major_group":"Hemiptera",     "flow":"IV"  }],
	["Corixidae",          { "major_group":"Hemiptera",     "flow":"IV"  }],
	["Haliplidae",         { "major_group":"Coleoptera",    "flow":"IV"  }],
	["Hygrobiidae",        { "major_group":"Coleoptera",    "flow":"V"   }],
	["Noteridae",          { "major_group":"Coleoptera",    "flow":"IV"  }],
	["Dytiscidae",         { "major_group":"Coleoptera",    "flow":"IV"  }],
	["Gyrinidae",          { "major_group":"Coleoptera",    "flow":"IV"  }],
	["Hydrophilidae",      { "major_group":"Coleoptera",    "flow":"IV"  }],
	["Hydraenidae",        { "major_group":"Coleoptera",    "flow":"IV"  }],
	["Scirtidae",          { "major_group":"Coleoptera",    "flow":"IV"  }],
	["Elmidae",            { "major_group":"Coleoptera",    "flow":"II"  }],
	["Sialidae",           { "major_group":"Megaloptera",   "flow":"IV"  }],
	["Osmylidae",          { "major_group":"Neuroptera",    "flow":"II"  }],
	["Sisyridae",          { "major_group":"Neuroptera",    "flow":"IV"  }],
	["Rhyacophilidae",     { "major_group":"Trichoptera",   "flow":"I"   }],
	["Glossosomatidae",    { "major_group":"Trichoptera",   "flow":"II"  }],
	["Philopotamidae",     { "major_group":"Trichoptera",   "flow":"I"   }],
	["Polycentropodidae",  { "major_group":"Trichoptera",   "flow":"IV"  }],
	["Psychomyiidae",      { "major_group":"Trichoptera",   "flow":"II"  }],
	["Ecnomidae",          { "major_group":"Trichoptera",   "flow":"III" }],
	["Hydropsychidae",     { "major_group":"Trichoptera",   "flow":"II"  }],
	["Hydroptilidae",      { "major_group":"Trichoptera",   "flow":"IV"  }],
	["Phryganeidae",       { "major_group":"Trichoptera",   "flow":"IV"  }],
	["Limnephilidae",      { "major_group":"Trichoptera",   "flow":"IV"  }],
	["Molannidae",         { "major_group":"Trichoptera",   "flow":"IV"  }],
	["Beraeidae",          { "major_group":"Trichoptera",   "flow":"II"  }],
	["Odontoceridae",      { "major_group":"Trichoptera",   "flow":"I"   }],
	["Leptoceridae",       { "major_group":"Trichoptera",   "flow":"IV"  }],
	["Goeridae",           { "major_group":"Trichoptera",   "flow":"I"   }],
	["Lepidostomatidae",   { "major_group":"Trichoptera",   "flow":"II"  }],
	["Brachycentridae",    { "major_group":"Trichoptera",   "flow":"II"  }],
	["Sericostomatidae",   { "major_group":"Trichoptera",   "flow":"II"  }],
	["Tipulidae",          { "major_group":"Diptera",       "flow":"IV"  }],
	["Ptychopteridae",     { "major_group":"Diptera",       "flow":"II"  }],
	["Chaoboridae",        { "major_group":"Diptera",       "flow":"V"   }],
	["Culicidae",          { "major_group":"Diptera",       "flow":"V"   }],
	["Simuliidae",         { "major_group":"Diptera",       "flow":"II"  }],
	["Syrphidae",          { "major_group":"Diptera",       "flow":"V"   }],
]);
