export interface IScoreBMWP {
    // family:            string,
    common_name:       string,
    score_orig:        number,
    score_rev:         number | null,
    score_riffle:      number | null,
    score_riffle_pool: number | null,
    score_pool:        number | null,
}

export const scoresBmwp: Map<string, IScoreBMWP> = new Map([
	["Planariidae",           { "common_name":" Flatworms",           "score_orig":5,  "score_rev":4.2,  "score_riffle":4.5,  "score_riffle_pool":4.1,  "score_pool":3.7  }],
	["Dendrocoelidae",        { "common_name":" Flatworms",           "score_orig":5,  "score_rev":3.1,  "score_riffle":2.3,  "score_riffle_pool":4.1,  "score_pool":3.1  }],
	["Neritidae",             { "common_name":" Snails",              "score_orig":6,  "score_rev":7.5,  "score_riffle":6.7,  "score_riffle_pool":8.1,  "score_pool":9.3  }],
	["Viviparidae",           { "common_name":" Snails",              "score_orig":6,  "score_rev":6.3,  "score_riffle":2.1,  "score_riffle_pool":4.7,  "score_pool":7.1  }],
	["Valvatidae",            { "common_name":" Snails",              "score_orig":3,  "score_rev":2.8,  "score_riffle":2.5,  "score_riffle_pool":2.5,  "score_pool":3.2  }],
	["Hydrobiidae",           { "common_name":" Snails",              "score_orig":3,  "score_rev":3.9,  "score_riffle":4.1,  "score_riffle_pool":3.9,  "score_pool":3.7  }],
	["Lymnaeidae",            { "common_name":" Snails",              "score_orig":3,  "score_rev":3,    "score_riffle":3.2,  "score_riffle_pool":3.1,  "score_pool":2.8  }],
	["Physidae",              { "common_name":" Snails",              "score_orig":3,  "score_rev":1.8,  "score_riffle":0.9,  "score_riffle_pool":1.5,  "score_pool":2.8  }],
	["Planorbidae",           { "common_name":" Snails",              "score_orig":3,  "score_rev":2.9,  "score_riffle":2.6,  "score_riffle_pool":2.9,  "score_pool":3.1  }],
	["Ancylidae",             { "common_name":" Limpets and Mussels", "score_orig":6,  "score_rev":5.6,  "score_riffle":5.5,  "score_riffle_pool":5.5,  "score_pool":6.2  }],
	["Unionidae",             { "common_name":" Limpets and Mussels", "score_orig":6,  "score_rev":5.2,  "score_riffle":4.7,  "score_riffle_pool":4.8,  "score_pool":5.5  }],
	["Sphaeriidae",           { "common_name":" Limpets and Mussels", "score_orig":3,  "score_rev":3.6,  "score_riffle":3.7,  "score_riffle_pool":3.7,  "score_pool":3.4  }],
	["Oligochaeta",           { "common_name":" Worms",               "score_orig":1,  "score_rev":3.5,  "score_riffle":3.9,  "score_riffle_pool":3.2,  "score_pool":2.5  }],
	["Piscicolidae",          { "common_name":" Leeches",             "score_orig":4,  "score_rev":5,    "score_riffle":4.5,  "score_riffle_pool":5.4,  "score_pool":5.2  }],
	["Glossiphoniidae",       { "common_name":" Leeches",             "score_orig":3,  "score_rev":3.1,  "score_riffle":3,    "score_riffle_pool":3.3,  "score_pool":2.9  }],
	["Hirudididae",           { "common_name":" Leeches",             "score_orig":3,  "score_rev":0,    "score_riffle":0.3,  "score_riffle_pool":-0.3, "score_pool":null }],
	["Erpobdellidae",         { "common_name":" Leeches",             "score_orig":3,  "score_rev":2.8,  "score_riffle":2.8,  "score_riffle_pool":2.8,  "score_pool":2.6  }],
	["Asellidae",             { "common_name":" Crustaceans",         "score_orig":3,  "score_rev":2.1,  "score_riffle":1.5,  "score_riffle_pool":2.4,  "score_pool":2.7  }],
	["Corophiidae",           { "common_name":" Crustaceans",         "score_orig":6,  "score_rev":6.1,  "score_riffle":5.4,  "score_riffle_pool":5.1,  "score_pool":6.5  }],
	["Gammaridae",            { "common_name":" Crustaceans",         "score_orig":6,  "score_rev":4.5,  "score_riffle":4.7,  "score_riffle_pool":4.3,  "score_pool":4.3  }],
	["Astacidae",             { "common_name":" Crustaceans",         "score_orig":8,  "score_rev":9,    "score_riffle":8.8,  "score_riffle_pool":9,    "score_pool":11.2 }],
	["Siphlonuridae",         { "common_name":" Mayflies",            "score_orig":10, "score_rev":11,   "score_riffle":11,   "score_riffle_pool":null, "score_pool":null }],
	["Baetidae",              { "common_name":" Mayflies",            "score_orig":4,  "score_rev":5.3,  "score_riffle":5.5,  "score_riffle_pool":4.8,  "score_pool":5.1  }],
	["Heptageniidae",         { "common_name":" Mayflies",            "score_orig":10, "score_rev":9.8,  "score_riffle":9.7,  "score_riffle_pool":10.7, "score_pool":13   }],
	["Leptophlebiidae",       { "common_name":" Mayflies",            "score_orig":10, "score_rev":8.9,  "score_riffle":8.7,  "score_riffle_pool":8.9,  "score_pool":9.9  }],
	["Ephemerellidae",        { "common_name":" Mayflies",            "score_orig":10, "score_rev":7.7,  "score_riffle":7.6,  "score_riffle_pool":8.1,  "score_pool":9.3  }],
	["Potamanthidae",         { "common_name":" Mayflies",            "score_orig":10, "score_rev":7.6,  "score_riffle":7.6,  "score_riffle_pool":null, "score_pool":null }],
	["Ephemeridae",           { "common_name":" Mayflies",            "score_orig":10, "score_rev":9.3,  "score_riffle":9,    "score_riffle_pool":9.2,  "score_pool":11   }],
	["Caenidae",              { "common_name":" Mayflies",            "score_orig":7,  "score_rev":7.1,  "score_riffle":7.2,  "score_riffle_pool":7.3,  "score_pool":6.4  }],
	["Taeniopterygidae",      { "common_name":" Stoneflies",          "score_orig":10, "score_rev":10.8, "score_riffle":10.7, "score_riffle_pool":12.1, "score_pool":null }],
	["Nemouridae",            { "common_name":" Stoneflies",          "score_orig":7,  "score_rev":9.1,  "score_riffle":9.2,  "score_riffle_pool":8.5,  "score_pool":8.8  }],
	["Leuctridae",            { "common_name":" Stoneflies",          "score_orig":10, "score_rev":9.9,  "score_riffle":9.8,  "score_riffle_pool":10.4, "score_pool":11.2 }],
	["Capniidae",             { "common_name":" Stoneflies",          "score_orig":10, "score_rev":10,   "score_riffle":10.1, "score_riffle_pool":null, "score_pool":null }],
	["Perlodidae",            { "common_name":" Stoneflies",          "score_orig":10, "score_rev":10.7, "score_riffle":10.8, "score_riffle_pool":10.7, "score_pool":10.9 }],
	["Perlidae",              { "common_name":" Stoneflies",          "score_orig":10, "score_rev":12.5, "score_riffle":12.5, "score_riffle_pool":12.2, "score_pool":null }],
	["Chloroperlidae",        { "common_name":" Stoneflies",          "score_orig":10, "score_rev":12.4, "score_riffle":12.5, "score_riffle_pool":12.1, "score_pool":null }],
	["Platycnemidae",         { "common_name":" Damselflies",         "score_orig":6,  "score_rev":5.1,  "score_riffle":3.6,  "score_riffle_pool":5.4,  "score_pool":5.7  }],
	["Coenagriidae",          { "common_name":" Damselflies",         "score_orig":6,  "score_rev":3.5,  "score_riffle":2.6,  "score_riffle_pool":3.3,  "score_pool":3.8  }],
	["Lestidae",              { "common_name":" Damselflies",         "score_orig":8,  "score_rev":5.4,  "score_riffle":null, "score_riffle_pool":null, "score_pool":5.4  }],
	["Calopterygidae",        { "common_name":" Damselflies",         "score_orig":8,  "score_rev":6.4,  "score_riffle":6,    "score_riffle_pool":6.1,  "score_pool":7.6  }],
	["Gomphidae",             { "common_name":" Dragonflies",         "score_orig":8,  "score_rev":null, "score_riffle":null, "score_riffle_pool":null, "score_pool":null }],
	["Cordulegasteridae",     { "common_name":" Dragonflies",         "score_orig":8,  "score_rev":8.6,  "score_riffle":9.5,  "score_riffle_pool":6.5,  "score_pool":7.6  }],
	["Aeshnidae",             { "common_name":" Dragonflies",         "score_orig":8,  "score_rev":6.1,  "score_riffle":7,    "score_riffle_pool":6.9,  "score_pool":5.7  }],
	["Corduliidae",           { "common_name":" Dragonflies",         "score_orig":8,  "score_rev":null, "score_riffle":null, "score_riffle_pool":null, "score_pool":null }],
	["Libellulidae",          { "common_name":" Dragonflies",         "score_orig":8,  "score_rev":5,    "score_riffle":null, "score_riffle_pool":null, "score_pool":5    }],
	// ["Mesoveliidae *",    { "common_name":" Bugs",                "score_orig":5,  "score_rev":4.7,  "score_riffle":4.9,  "score_riffle_pool":4,    "score_pool":5.1}],
	["Hydrometridae",         { "common_name":" Bugs",                "score_orig":5,  "score_rev":5.3,  "score_riffle":5,    "score_riffle_pool":6.2,  "score_pool":4.9  }],
	["Gerridae",              { "common_name":" Bugs",                "score_orig":5,  "score_rev":4.7,  "score_riffle":4.5,  "score_riffle_pool":5,    "score_pool":4.7  }],
	["Nepidae",               { "common_name":" Bugs",                "score_orig":5,  "score_rev":4.3,  "score_riffle":4.1,  "score_riffle_pool":4.2,  "score_pool":4.5  }],
	["Naucoridae",            { "common_name":" Bugs",                "score_orig":5,  "score_rev":4.3,  "score_riffle":null, "score_riffle_pool":null, "score_pool":4.3  }],
	["Aphelocheiridae",       { "common_name":" Bugs",                "score_orig":10, "score_rev":8.9,  "score_riffle":8.4,  "score_riffle_pool":9.5,  "score_pool":11.7 }],
	["Notonectidae",          { "common_name":" Bugs",                "score_orig":5,  "score_rev":3.8,  "score_riffle":1.8,  "score_riffle_pool":3.4,  "score_pool":4.4  }],
	["Pleidae",               { "common_name":" Bugs",                "score_orig":5,  "score_rev":3.9,  "score_riffle":null, "score_riffle_pool":null, "score_pool":3.9  }],
	["Corixidae",             { "common_name":" Bugs",                "score_orig":5,  "score_rev":3.7,  "score_riffle":3.6,  "score_riffle_pool":3.5,  "score_pool":3.9  }],
	["Haliplidae",            { "common_name":" Beetles",             "score_orig":5,  "score_rev":4,    "score_riffle":3.7,  "score_riffle_pool":4.2,  "score_pool":4.3  }],
	["Hygrobiidae",           { "common_name":" Beetles",             "score_orig":5,  "score_rev":2.6,  "score_riffle":5.6,  "score_riffle_pool":-0.8, "score_pool":2.6  }],
	["Dytiscidae",            { "common_name":" Beetles",             "score_orig":5,  "score_rev":4.8,  "score_riffle":5.2,  "score_riffle_pool":4.3,  "score_pool":4.2  }],
	["Gyrinidae",             { "common_name":" Beetles",             "score_orig":5,  "score_rev":7.8,  "score_riffle":8.1,  "score_riffle_pool":7.4,  "score_pool":6.8  }],
	["Hydrophilidae",         { "common_name":" Beetles",             "score_orig":5,  "score_rev":5.1,  "score_riffle":5.5,  "score_riffle_pool":4.5,  "score_pool":3.9  }],
	["Clambidae",             { "common_name":" Beetles",             "score_orig":5,  "score_rev":null, "score_riffle":null, "score_riffle_pool":null, "score_pool":null }],
	["Scirtidae",             { "common_name":" Beetles",             "score_orig":5,  "score_rev":6.5,  "score_riffle":6.9,  "score_riffle_pool":6.2,  "score_pool":5.8  }],
	["Dryopidae",             { "common_name":" Beetles",             "score_orig":5,  "score_rev":6.5,  "score_riffle":6.5,  "score_riffle_pool":null, "score_pool":null }],
	["Elmidae",               { "common_name":" Beetles",             "score_orig":5,  "score_rev":6.4,  "score_riffle":6.5,  "score_riffle_pool":6.1,  "score_pool":6.5  }],
	// ["Chrysomelidae *",   { "common_name":" Beetles",             "score_orig":5,  "score_rev":4.2,  "score_riffle":4.9,  "score_riffle_pool":1.1,  "score_pool":4.1}],
	// ["Curculionidae *",   { "common_name":" Beetles",             "score_orig":5,  "score_rev":4,    "score_riffle":4.7,  "score_riffle_pool":3.1,  "score_pool":2.9}],
	["Sialidae",              { "common_name":" Alderflies",          "score_orig":4,  "score_rev":4.5,  "score_riffle":4.7,  "score_riffle_pool":4.7,  "score_pool":4.3  }],
	["Rhyacophilidae",        { "common_name":" Caddisflies",         "score_orig":7,  "score_rev":8.3,  "score_riffle":8.2,  "score_riffle_pool":8.6,  "score_pool":9.6  }],
	["Philopotamidae",        { "common_name":" Caddisflies",         "score_orig":8,  "score_rev":10.6, "score_riffle":10.7, "score_riffle_pool":9.8,  "score_pool":null }],
	["Polycentropidae",       { "common_name":" Caddisflies",         "score_orig":7,  "score_rev":8.6,  "score_riffle":8.6,  "score_riffle_pool":8.4,  "score_pool":8.7  }],
	["Psychomyiidae",         { "common_name":" Caddisflies",         "score_orig":8,  "score_rev":6.9,  "score_riffle":6.4,  "score_riffle_pool":7.4,  "score_pool":8    }],
	["Hydropsychidae",        { "common_name":" Caddisflies",         "score_orig":5,  "score_rev":6.6,  "score_riffle":6.6,  "score_riffle_pool":6.5,  "score_pool":7.2  }],
	["Hydroptilidae",         { "common_name":" Caddisflies",         "score_orig":6,  "score_rev":6.7,  "score_riffle":6.7,  "score_riffle_pool":6.8,  "score_pool":6.5  }],
	["Phryganeidae",          { "common_name":" Caddisflies",         "score_orig":10, "score_rev":7,    "score_riffle":6.6,  "score_riffle_pool":5.4,  "score_pool":8    }],
	["Limnephilidae",         { "common_name":" Caddisflies",         "score_orig":7,  "score_rev":6.9,  "score_riffle":7.1,  "score_riffle_pool":6.5,  "score_pool":6.6  }],
	["Molannidae",            { "common_name":" Caddisflies",         "score_orig":10, "score_rev":8.9,  "score_riffle":7.8,  "score_riffle_pool":8.1,  "score_pool":10   }],
	["Beraeidae",             { "common_name":" Caddisflies",         "score_orig":10, "score_rev":9,    "score_riffle":8.3,  "score_riffle_pool":7.8,  "score_pool":10   }],
	["Odontoceridae",         { "common_name":" Caddisflies",         "score_orig":10, "score_rev":10.9, "score_riffle":10.8, "score_riffle_pool":11.4, "score_pool":11.7 }],
	["Leptoceridae",          { "common_name":" Caddisflies",         "score_orig":10, "score_rev":7.8,  "score_riffle":7.8,  "score_riffle_pool":7.7,  "score_pool":8.1  }],
	["Goeridae",              { "common_name":" Caddisflies",         "score_orig":10, "score_rev":9.9,  "score_riffle":9.8,  "score_riffle_pool":9.6,  "score_pool":12.4 }],
	["Lepidostomatidae",      { "common_name":" Caddisflies",         "score_orig":10, "score_rev":10.4, "score_riffle":10.3, "score_riffle_pool":10.7, "score_pool":11.6 }],
	["Brachycentridae",       { "common_name":" Caddisflies",         "score_orig":10, "score_rev":9.4,  "score_riffle":9.3,  "score_riffle_pool":9.7,  "score_pool":11   }],
	["Sericostomatidae",      { "common_name":" Caddisflies",         "score_orig":10, "score_rev":9.2,  "score_riffle":9.1,  "score_riffle_pool":9.3,  "score_pool":10.3 }],
	["Tipulidae",             { "common_name":" True flies",          "score_orig":5,  "score_rev":5.5,  "score_riffle":5.6,  "score_riffle_pool":5,    "score_pool":5.1  }],
	["Chironomidae",          { "common_name":" True flies",          "score_orig":2,  "score_rev":3.7,  "score_riffle":4.1,  "score_riffle_pool":3.4,  "score_pool":2.8  }],
	["Simuliidae",            { "common_name":" True flies",          "score_orig":5,  "score_rev":5.8,  "score_riffle":5.9,  "score_riffle_pool":5.1,  "score_pool":5.5  }],
]);

// Source: http://www.cies.staffs.ac.uk/bmwptabl.htm
//
//  * These families are now excluded from the list used for the calculation of the score.
//    A blank indicates that there were insufficient records for the calculations.
//
// The Revised BMWP Scores are based on the analysis of frequency of occurrence of the families
// recorded in approximately 17,000 samples.
//
// The Habitat Specific Scores are based on the following substrate compositions:
// Riffles: >= 70% boulders and pebbles    Pool: >= 70% sand and silt    Riffle/Pool: the remainder

export interface IScoreWHPT {
    // family:      string,
    score_presence: number,
    scores:         number[],
}

export const scoresWhpt: Map<string, IScoreWHPT> = new Map([
	["Planariidae",       { "score_presence": 4.9,  "scores": [4.7,  5.4,  5.4,  5.4 ] }],
	["Dugesiidae",        { "score_presence": 2.9,  "scores": [2.8,  3.1,  3.1,  3.1 ] }],
	["Dendrocoelidae",    { "score_presence": 3,    "scores": [3,    2.6,  2.6,  2.6 ] }],
	["Neritidae",         { "score_presence": 6.4,  "scores": [6.4,  6.5,  6.9,  6.9 ] }],
	["Viviparidae",       { "score_presence": 5.7,  "scores": [5.2,  6.7,  6.7,  6.7 ] }],
	["Valvatidae",        { "score_presence": 3.2,  "scores": [3.3,  3.1,  2.7,  2.7 ] }],
	["Hydrobiidae",       { "score_presence": 4.2,  "scores": [4.1,  4.2,  4.6,  3.7 ] }],
	["Bithyniidae",       { "score_presence": 3.7,  "scores": [3.6,  3.8,  3.3,  3.3 ] }],
	["Physidae",          { "score_presence": 2.4,  "scores": [2.7,  2,    0.4,  0.4 ] }],
	["Lymnaeidae",        { "score_presence": 3.3,  "scores": [3.6,  2.5,  1.2,  1.2 ] }],
	["Planorbidae",       { "score_presence": 3.1,  "scores": [3.2,  3,    2.4,  2.4 ] }],
	["Ancylidae",         { "score_presence": 5.7,  "scores": [5.8,  5.5,  5.5,  5.5 ] }],
	["Acroloxidae",       { "score_presence": 3.6,  "scores": [3.6,  3.8,  3.8,  3.8 ] }],
	["Unionidae",         { "score_presence": 5.3,  "scores": [5.2,  6.8,  6.8,  6.8 ] }],
	["Sphaeriidae",       { "score_presence": 3.9,  "scores": [4.4,  3.5,  3.4,  2.3 ] }],
	["Dreissenidae",      { "score_presence": 3.7,  "scores": [3.7,  3.7,  3.7,  3.7 ] }],
	["Oligochaeta",       { "score_presence": 2.7,  "scores": [3.6,  2.3,  1.4,  -0.6] }],
	["Piscicolidae",      { "score_presence": 5.2,  "scores": [5.2,  4.9,  4.9,  4.9 ] }],
	["Glossiphoniidae",   { "score_presence": 3.2,  "scores": [3.4,  2.5,  0.8,  0.8 ] }],
	["Hirudinidae",       { "score_presence": -0.8, "scores": [-0.8, -0.8, -0.8, -0.8] }],
	["Erpobdellidae",     { "score_presence": 3.1,  "scores": [3.6,  2,    -0.8, -0.8] }],
	["Astacidae",         { "score_presence": 7.9,  "scores": [7.9,  7.9,  7.9,  7.9 ] }],
	["Asellidae",         { "score_presence": 2.8,  "scores": [4,    2.3,  0.8,  -1.6] }],
	["Corophiidae",       { "score_presence": 5.8,  "scores": [5.7,  5.8,  5.8,  5.8 ] }],
	["Crangonyctidae",    { "score_presence": 3.9,  "scores": [3.8,  4,    3.6,  3.6 ] }],
	["Gammaridae",        { "score_presence": 4.4,  "scores": [4.2,  4.5,  4.6,  3.9 ] }],
	["Niphargidae",       { "score_presence": 6.3,  "scores": [6.3,  6.3,  6.3,  6.3 ] }],
	["Siphlonuridae",     { "score_presence": 11.5, "scores": [11.3, 12.2, 12.2, 12.2] }],
	["Baetidae",          { "score_presence": 5.5,  "scores": [3.6,  5.9,  7.2,  7.5 ] }],
	["Heptageniidae",     { "score_presence": 9.7,  "scores": [8.5,  10.3, 11.1, 11.1] }],
	["Leptophlebiidae",   { "score_presence": 8.8,  "scores": [8.8,  9.1,  9.2,  9.2 ] }],
	["Potamanthidae",     { "score_presence": 10,   "scores": [9.8,  10.4, 10.4, 10.4] }],
	["Ephemeridae",       { "score_presence": 8.4,  "scores": [8.3,  8.8,  9.4,  9.4 ] }],
	["Ephemerellidae",    { "score_presence": 8.2,  "scores": [7.9,  8.5,  9,    9   ] }],
	["Caenidae",          { "score_presence": 6.5,  "scores": [6.5,  6.5,  6.5,  6.5 ] }],
	["Taeniopterygidae",  { "score_presence": 11.3, "scores": [11,   11.9, 12.1, 12.1] }],
	["Nemouridae",        { "score_presence": 9.3,  "scores": [8.7,  10.7, 10.7, 10.7] }],
	["Leuctridae",        { "score_presence": 10,   "scores": [9.3,  10.6, 10.6, 10.6] }],
	["Capniidae",         { "score_presence": 9.6,  "scores": [9.7,  9.4,  9.4,  9.4 ] }],
	["Perlodidae",        { "score_presence": 10.8, "scores": [10.5, 11.5, 11.5, 11.5] }],
	["Perlidae",          { "score_presence": 12.7, "scores": [12.6, 13,   13,   13  ] }],
	["Chloroperlidae",    { "score_presence": 11.6, "scores": [11.4, 12.2, 12.2, 12.2] }],
	["Platycnemididae",   { "score_presence": 6,    "scores": [6,    6,    6,    6   ] }],
	["Coenagriidae",      { "score_presence": 3.5,  "scores": [3.4,  3.8,  3.8,  3.8 ] }],
	["Calopterygidae",    { "score_presence": 6,    "scores": [5.9,  6.2,  6.2,  6.2 ] }],
	["Cordulegasteridae", { "score_presence": 9.8,  "scores": [9.8,  9.8,  9.8,  9.8 ] }],
	["Aeshnidae",         { "score_presence": 4.7,  "scores": [4.7,  4.7,  4.7,  4.7 ] }],
	["Libellulidae",      { "score_presence": 4.1,  "scores": [4.1,  4.1,  4.1,  4.1 ] }],
	["Mesoveliidae",      { "score_presence": 4.7,  "scores": [4.7,  4.7,  4.7,  4.7 ] }],
	["Hydrometridae",     { "score_presence": 4.3,  "scores": [4.3,  4.3,  4.3,  4.3 ] }],
	["Veliidae",          { "score_presence": 4.5,  "scores": [4.5,  3.9,  3.9,  3.9 ] }],
	["Gerridae",          { "score_presence": 5.2,  "scores": [5.2,  5.5,  5.5,  5.5 ] }],
	["Nepidae",           { "score_presence": 2.9,  "scores": [2.9,  2.9,  2.9,  2.9 ] }],
	["Naucoridae",        { "score_presence": 3.7,  "scores": [3.7,  3.7,  3.7,  3.7 ] }],
	["Aphelocheiridae",   { "score_presence": 8.5,  "scores": [8.6,  8.5,  8,    8   ] }],
	["Notonectidae",      { "score_presence": 3.4,  "scores": [3.4,  3.9,  3.9,  3.9 ] }],
	["Pleidae",           { "score_presence": 3.3,  "scores": [3.3,  3.3,  3.3,  3.3 ] }],
	["Corixidae",         { "score_presence": 3.8,  "scores": [3.7,  3.9,  3.7,  3.7 ] }],
	["Haliplidae",        { "score_presence": 3.6,  "scores": [3.6,  3.4,  3.4,  3.4 ] }],
	["Hygrobiidae",       { "score_presence": 3.8,  "scores": [3.8,  3.8,  3.8,  3.8 ] }],
	["Noteridae",         { "score_presence": 3.2,  "scores": [3.2,  3.2,  3.2,  3.2 ] }],
	["Dytiscidae",        { "score_presence": 4.5,  "scores": [4.5,  4.8,  4.8,  4.8 ] }],
	["Gyrinidae",         { "score_presence": 8.2,  "scores": [8.1,  9,    9,    9   ] }],
	["Hydrophilidae",     { "score_presence": 6.2,  "scores": [5.8,  8.8,  8.8,  8.8 ] }],
	["Hydraenidae",       { "score_presence": 8.9,  "scores": [8.5,  10.5, 10.5, 10.5] }],
	["Scirtidae",         { "score_presence": 6.9,  "scores": [6.9,  6.8,  6.8,  6.8 ] }],
	["Dryopidae",         { "score_presence": 6,    "scores": [6,    6,    6,    6   ] }],
	["Elmidae",           { "score_presence": 6.6,  "scores": [5.3,  7.4,  8.3,  8.3 ] }],
	["Sialidae",          { "score_presence": 4.3,  "scores": [4.2,  4.4,  4.4,  4.4 ] }],
	["Sisyridae",         { "score_presence": 5.7,  "scores": [5.7,  5.7,  5.7,  5.7 ] }],
	["Rhyacophilidae",    { "score_presence": 8.4,  "scores": [8.1,  9.2,  8.3,  8.3 ] }],
	["Glossosomatidae",   { "score_presence": 7.7,  "scores": [7.8,  7.6,  7.2,  7.2 ] }],
	["Hydroptilidae",     { "score_presence": 6.2,  "scores": [6.1,  6.5,  6.8,  6.8 ] }],
	["Philopotamidae",    { "score_presence": 11.2, "scores": [11.2, 11.1, 11.1, 11.1] }],
	["Psychomyiidae",     { "score_presence": 5.8,  "scores": [5.8,  5.7,  5.7,  5.7 ] }],
	["Polycentropodidae", { "score_presence": 8.1,  "scores": [8.2,  8.1,  8.1,  8.1 ] }],
	["Hydropsychidae",    { "score_presence": 6.6,  "scores": [5.8,  7.2,  7.4,  7.4 ] }],
	["Phryganeidae",      { "score_presence": 5.5,  "scores": [5.5,  5.5,  5.5,  5.5 ] }],
	["Brachycentridae",   { "score_presence": 9.5,  "scores": [9.6,  9.5,  8.9,  8.9 ] }],
	["Lepidostomatidae",  { "score_presence": 10.1, "scores": [9.9,  10.3, 10.2, 10.2] }],
	["Limnephilidae",     { "score_presence": 6.2,  "scores": [5.9,  6.9,  6.9,  6.9 ] }],
	["Goeridae",          { "score_presence": 8.8,  "scores": [8.8,  8.8,  9.4,  9.4 ] }],
	["Beraeidae",         { "score_presence": 8.7,  "scores": [8.8,  7.3,  7.3,  7.3 ] }],
	["Sericostomatidae",  { "score_presence": 9.1,  "scores": [8.9,  9.4,  9.5,  9.5 ] }],
	["Odontoceridae",     { "score_presence": 11,   "scores": [11.1, 10.3, 10.3, 10.3] }],
	["Molannidae",        { "score_presence": 6.6,  "scores": [6.5,  7.6,  7.6,  7.6 ] }],
	["Leptoceridae",      { "score_presence": 6.7,  "scores": [6.7,  6.9,  7.1,  7.1 ] }],
	["Tipulidae",         { "score_presence": 5.9,  "scores": [5.4,  6.9,  6.9,  7.1 ] }],
	["Psychodidae",       { "score_presence": 4.4,  "scores": [4.5,  3,    3,    3   ] }],
	["Ptychopteridae",    { "score_presence": 6.4,  "scores": [6.4,  6.4,  6.4,  6.4 ] }],
	["Dixidae",           { "score_presence": 7,    "scores": [7,    7,    7,    7   ] }],
	["Chaoboridae",       { "score_presence": 3,    "scores": [3,    3,    3,    3   ] }],
	["Culicidae",         { "score_presence": 2,    "scores": [2,    1.9,  1.9,  1.9 ] }],
	["Ceratopogonidae",   { "score_presence": 5.5,  "scores": [5.4,  5.5,  5.5,  5.5 ] }],
	["Simuliidae",        { "score_presence": 5.8,  "scores": [5.5,  6.1,  5.8,  3.9 ] }],
	["Chironomidae",      { "score_presence": 1.1,  "scores": [1.2,  1.3,  -0.9, -0.9] }],
	["Stratiomyidae",     { "score_presence": 3.6,  "scores": [3.6,  3.6,  3.6,  3.6 ] }],
	["Rhagionidae",       { "score_presence": 9.6,  "scores": [9.6,  9.6,  9.6,  9.6 ] }],
	["Tabanidae",         { "score_presence": 7.1,  "scores": [7.1,  7.3,  7.3,  7.3 ] }],
	["Athericidae",       { "score_presence": 9.3,  "scores": [9.3,  9.5,  9.5,  9.5 ] }],
	["Empididae",         { "score_presence": 7.1,  "scores": [7,    7.6,  7.6,  7.6 ] }],
	["Dolichopodidae",    { "score_presence": 4.9,  "scores": [4.9,  4.9,  4.9,  4.9 ] }],
	["Syrphidae",         { "score_presence": 1.9,  "scores": [1.9,  1.9,  1.9,  1.9 ] }],
	["Sciomyzidae",       { "score_presence": 3.4,  "scores": [3.4,  3.4,  3.4,  3.4 ] }],
	["Ephydridae",        { "score_presence": 4.4,  "scores": [4.4,  4.4,  4.4,  4.4 ] }],
	["Muscidae",          { "score_presence": 3.9,  "scores": [4,    2.6,  2.6,  2.6 ] }],
]);

export default { scoresBmwp, scoresWhpt };
